-- MakerACC-Development only. Existing synthetic masters/actor; every change rolls back.
begin;
do $$
declare
  f record; draft record; posted record; replay record; reversed record; reverse_replay record;
  advance record; payment record; release record; accountant_draft record; completed_draft record;
  blocked_draft record; cap_draft record; large_draft record; test_role public.company_role;
  previous_work bigint; live_gross bigint; revised bigint; retention bigint; net bigint; vat bigint; payable bigint;
  payment_amount bigint; release_amount bigint; foreign_company uuid; deduction_type public.certificate_deduction_type;
  post_key uuid:=gen_random_uuid(); reverse_key uuid:=gen_random_uuid();
begin
  select m.user_id,m.role original_role,c.id company_id,s.id subcontract_id,s.project_id,s.subcontractor_id,
    s.retention_bps,t.id treasury_id
  into f
  from public.company_memberships m join public.profiles pf on pf.user_id=m.user_id and pf.status='ACTIVE'
  join public.companies c on c.id=m.company_id and c.status='ACTIVE'
  join public.subcontracts s on s.company_id=c.id and s.status='ACTIVE' and s.retention_bps between 1 and 5000
  join public.projects pr on pr.company_id=c.id and pr.id=s.project_id and pr.status<>'CLOSED'
  join public.parties p on p.company_id=c.id and p.id=s.subcontractor_id and p.type='SUBCONTRACTOR'
  join public.treasury_accounts t on t.company_id=c.id and t.status='ACTIVE' and (t.project_id is null or t.project_id=s.project_id)
  join public.accounts ta on ta.company_id=c.id and ta.id=t.gl_account_id and ta.status='ACTIVE' and ta.account_type='ASSET'
  where m.status='ACTIVE' and exists(select 1 from public.certificate_deduction_account_mappings dm join public.accounts da on da.id=dm.account_id and da.company_id=dm.company_id and da.status='ACTIVE' and da.account_type='REVENUE' where dm.company_id=c.id)
    and exists(select 1 from public.accounts a where a.company_id=c.id and a.status='ACTIVE' and a.system_key in ('PROJECT_COST_SUBCONTRACTORS','INPUT_VAT','SUBCONTRACTOR_RETENTION_PAYABLE','SUBCONTRACTOR_ADVANCE','SUBCONTRACTOR_PAYABLE') group by a.company_id having count(distinct a.system_key)=5)
    and (s.original_contract_value_minor::numeric+s.approved_variations_minor::numeric-coalesce((select sum(sc.gross_certified_minor) from public.subcontractor_certificates sc where sc.company_id=c.id and sc.subcontract_id=s.id and sc.status='POSTED'),0))>=30000
  order by c.id,m.user_id,s.id,t.id limit 1;
  if f.user_id is null then raise exception 'No synthetic Certificate fixture'; end if;
  select dm.deduction_type into deduction_type from public.certificate_deduction_account_mappings dm where dm.company_id=f.company_id order by dm.deduction_type limit 1;
  select coalesce(max(work_value_to_date_minor),0),coalesce(sum(gross_certified_minor),0) into previous_work,live_gross from public.subcontractor_certificates where company_id=f.company_id and subcontract_id=f.subcontract_id and status='POSTED';
  select original_contract_value_minor+approved_variations_minor into revised from public.subcontracts where id=f.subcontract_id;
  update public.company_memberships set role='ACCOUNTING_ADMIN' where company_id=f.company_id and user_id=f.user_id;
  perform set_config('request.jwt.claim.sub',f.user_id::text,true);set local role authenticated;
  select * into advance from public.post_subcontractor_advance(f.company_id,current_date,f.subcontract_id,f.treasury_id,5000,'TRANSFER','P6D cert rollback','recovery fixture',gen_random_uuid());
  select * into draft from public.create_subcontractor_certificate_draft(f.company_id,current_date,f.subcontract_id,'P6D-CERT-'||gen_random_uuid()::text,previous_work+10000,0,1000,'AUTO_5',null,true,'P6D-TAX',current_date,jsonb_build_array(jsonb_build_object('type',deduction_type,'description','Focused deduction','amount_minor',500)), 'rollback certificate');
  reset role;
  if not exists(select 1 from public.subcontractor_certificates c where c.id=draft.subcontractor_certificate_id and c.status='DRAFT' and c.previous_certified_work_minor is null and c.gross_certified_minor is null and c.posted_journal_entry_id is null) or exists(select 1 from public.journal_entries j where j.source_type='SUBCONTRACTOR_CERTIFICATE' and j.source_id=draft.subcontractor_certificate_id) then raise exception 'Draft created accounting truth'; end if;
  set local role authenticated;select * into posted from public.approve_post_subcontractor_certificate(f.company_id,draft.subcontractor_certificate_id,post_key);select * into replay from public.approve_post_subcontractor_certificate(f.company_id,draft.subcontractor_certificate_id,post_key);reset role;
  if posted.replayed or not replay.replayed or posted.journal_entry_id<>replay.journal_entry_id then raise exception 'Approval replay mismatch'; end if;
  retention:=round(10000*f.retention_bps::numeric/10000);net:=10000-retention-1000-500;vat:=round(net*5/100);payable:=net+vat;
  if not exists(select 1 from public.subcontractor_certificates c where c.id=draft.subcontractor_certificate_id and c.status='POSTED' and c.previous_certified_work_minor=previous_work and c.current_work_amount_minor=10000 and c.gross_certified_minor=10000 and c.retention_amount_minor=retention and c.advance_recovery_minor=1000 and c.deductions_total_minor=500 and c.net_before_vat_minor=net and c.vat_amount_minor=vat and c.payable_amount_minor=payable and c.posted_journal_entry_id=posted.journal_entry_id) then raise exception 'Server Certificate calculation mismatch'; end if;
  if (select sum(debit_minor-credit_minor) from public.journal_lines where journal_entry_id=posted.journal_entry_id)<>0 or exists(select 1 from public.journal_lines where journal_entry_id=posted.journal_entry_id and treasury_account_id is not null) or exists(select 1 from public.journal_lines l join public.accounts a on a.id=l.account_id where l.journal_entry_id=posted.journal_entry_id and a.system_key not in ('PROJECT_COST_SUBCONTRACTORS','INPUT_VAT','SUBCONTRACTOR_RETENTION_PAYABLE','SUBCONTRACTOR_ADVANCE','SUBCONTRACTOR_PAYABLE') and l.account_id not in (select account_id from public.subcontractor_certificate_deductions where certificate_id=draft.subcontractor_certificate_id)) then raise exception 'Certificate journal balance/account/Treasury mismatch'; end if;
  if not exists(select 1 from public.journal_lines l join public.accounts a on a.id=l.account_id where l.journal_entry_id=posted.journal_entry_id and a.system_key='PROJECT_COST_SUBCONTRACTORS' and l.debit_minor=10000 and l.project_id=f.project_id and l.party_id=f.subcontractor_id and l.subcontract_id=f.subcontract_id) or not exists(select 1 from public.journal_lines l join public.accounts a on a.id=l.account_id where l.journal_entry_id=posted.journal_entry_id and a.system_key='INPUT_VAT' and l.debit_minor=vat) then raise exception 'Certificate cost/VAT lines mismatch'; end if;

  -- Exact upper-bound draft transport, Accountant preparation, and role/RLS matrix.
  set local role authenticated;select * into large_draft from public.create_subcontractor_certificate_draft(f.company_id,current_date,f.subcontract_id,'P6D-LARGE-'||gen_random_uuid()::text,9000000000000000,0,0,'ZERO',null,false,null,null,'[]',null);reset role;
  foreach test_role in array enum_range(null::public.company_role) loop
    update public.company_memberships set role=test_role where company_id=f.company_id and user_id=f.user_id;set local role authenticated;
    if test_role in ('ACCOUNTING_ADMIN','ACCOUNTANT','MANAGEMENT_VIEWER') then if not exists(select 1 from public.subcontractor_certificates where id=draft.subcontractor_certificate_id) then raise exception 'Allowed Certificate read failed: %',test_role;end if;elsif exists(select 1 from public.subcontractor_certificates where id=draft.subcontractor_certificate_id) then raise exception 'Denied Certificate read: %',test_role;end if;
    if test_role='ACCOUNTANT' then select * into accountant_draft from public.create_subcontractor_certificate_draft(f.company_id,current_date,f.subcontract_id,'P6D-ACCOUNTANT-'||gen_random_uuid()::text,previous_work+11000,0,0,'ZERO',null,false,null,null,'[]',null);elsif test_role<>'ACCOUNTING_ADMIN' then begin perform public.create_subcontractor_certificate_draft(f.company_id,current_date,f.subcontract_id,'P6D-DENIED-'||gen_random_uuid()::text,previous_work+11000,0,0,'ZERO',null,false,null,null,'[]',null);raise exception 'Denied draft created: %',test_role;exception when insufficient_privilege then null;end;end if;
    if test_role<>'ACCOUNTING_ADMIN' then begin perform public.approve_post_subcontractor_certificate(f.company_id,draft.subcontractor_certificate_id,gen_random_uuid());raise exception 'Denied approval: %',test_role;exception when insufficient_privilege then null;end;begin perform public.reverse_subcontractor_certificate(f.company_id,draft.subcontractor_certificate_id,current_date,'Denied',gen_random_uuid());raise exception 'Denied reversal: %',test_role;exception when insufficient_privilege then null;end;end if;reset role;
  end loop;
  update public.company_memberships set role='ACCOUNTING_ADMIN',status='INACTIVE' where company_id=f.company_id and user_id=f.user_id;set local role authenticated;begin perform public.create_subcontractor_certificate_draft(f.company_id,current_date,f.subcontract_id,'P6D-INACTIVE-'||gen_random_uuid()::text,previous_work+11000,0,0,'ZERO',null,false,null,null,'[]',null);raise exception 'Inactive member created draft';exception when insufficient_privilege then null;end;reset role;update public.company_memberships set status='ACTIVE' where company_id=f.company_id and user_id=f.user_id;
  select c.id into foreign_company from public.companies c where c.id<>f.company_id and not exists(select 1 from public.company_memberships m where m.company_id=c.id and m.user_id=f.user_id and m.status='ACTIVE') limit 1;set local role authenticated;begin perform public.create_subcontractor_certificate_draft(foreign_company,current_date,f.subcontract_id,'P6D-CROSS-'||gen_random_uuid()::text,1,0,0,'ZERO',null,false,null,null,'[]',null);raise exception 'Cross-tenant draft created';exception when insufficient_privilege then null;end;reset role;

  -- Canonical lifecycle behavior.
  update public.parties set status='INACTIVE' where id=f.subcontractor_id;update public.subcontracts set status='COMPLETED' where id=f.subcontract_id;set local role authenticated;select * into completed_draft from public.create_subcontractor_certificate_draft(f.company_id,current_date,f.subcontract_id,'P6D-COMPLETED-'||gen_random_uuid()::text,previous_work+11000,0,0,'ZERO',null,false,null,null,'[]',null);perform public.approve_post_subcontractor_certificate(f.company_id,completed_draft.subcontractor_certificate_id,gen_random_uuid());reset role;update public.subcontracts set status='CLOSED' where id=f.subcontract_id;set local role authenticated;select * into blocked_draft from public.create_subcontractor_certificate_draft(f.company_id,current_date,f.subcontract_id,'P6D-CLOSED-'||gen_random_uuid()::text,previous_work+12000,0,0,'ZERO',null,false,null,null,'[]',null);begin perform public.approve_post_subcontractor_certificate(f.company_id,blocked_draft.subcontractor_certificate_id,gen_random_uuid());raise exception 'CLOSED Subcontract approved';exception when check_violation then null;end;reset role;update public.subcontracts set status='ACTIVE' where id=f.subcontract_id;update public.parties set status='ACTIVE' where id=f.subcontractor_id;
  set local role authenticated;select * into cap_draft from public.create_subcontractor_certificate_draft(f.company_id,current_date,f.subcontract_id,'P6D-CAP-'||gen_random_uuid()::text,previous_work+(revised-live_gross)+1,0,0,'ZERO',null,false,null,null,'[]',null);begin perform public.approve_post_subcontractor_certificate(f.company_id,cap_draft.subcontractor_certificate_id,gen_random_uuid());raise exception 'Revised-value cap exceeded';exception when check_violation then null;end;reset role;

  -- Live Payment and Retention Release dependencies, then exact reversal and replay.
  payment_amount:=least(payable,100);release_amount:=least(retention,100);set local role authenticated;
  select * into payment from public.post_subcontractor_payment(f.company_id,current_date,f.subcontract_id,f.treasury_id,payment_amount,'TRANSFER',null,'dependency',jsonb_build_array(jsonb_build_object('certificate_id',draft.subcontractor_certificate_id,'amount_minor',payment_amount)),gen_random_uuid());
  begin perform public.reverse_subcontractor_certificate(f.company_id,draft.subcontractor_certificate_id,current_date,'Blocked payment',gen_random_uuid());raise exception 'Certificate reversed with live Payment';exception when check_violation then null;end;
  perform public.reverse_subcontractor_payment(f.company_id,payment.subcontractor_payment_id,current_date,'Remove dependency',gen_random_uuid());
  select * into release from public.post_subcontractor_retention_release(f.company_id,current_date,f.subcontract_id,release_amount,null,'dependency',jsonb_build_array(jsonb_build_object('certificate_id',draft.subcontractor_certificate_id,'amount_minor',release_amount)),gen_random_uuid());
  begin perform public.reverse_subcontractor_certificate(f.company_id,draft.subcontractor_certificate_id,current_date,'Blocked release',gen_random_uuid());raise exception 'Certificate reversed with live Retention Release';exception when check_violation then null;end;
  perform public.reverse_subcontractor_retention_release(f.company_id,release.retention_release_id,current_date,'Remove dependency',gen_random_uuid());
  select * into reversed from public.reverse_subcontractor_certificate(f.company_id,draft.subcontractor_certificate_id,current_date,'Focused exact reversal',reverse_key);select * into reverse_replay from public.reverse_subcontractor_certificate(f.company_id,draft.subcontractor_certificate_id,current_date,'Focused exact reversal',reverse_key);reset role;
  if reversed.replayed or not reverse_replay.replayed or reversed.reversal_journal_entry_id<>reverse_replay.reversal_journal_entry_id or exists(select 1 from public.journal_lines o full join public.journal_lines r on r.journal_entry_id=reversed.reversal_journal_entry_id and r.line_number=o.line_number where o.journal_entry_id=posted.journal_entry_id and (r.account_id<>o.account_id or r.debit_minor<>o.credit_minor or r.credit_minor<>o.debit_minor or r.project_id is distinct from o.project_id or r.party_id is distinct from o.party_id or r.subcontract_id is distinct from o.subcontract_id or r.treasury_account_id is distinct from o.treasury_account_id)) then raise exception 'Exact Certificate reversal mismatch';end if;
  update public.company_memberships set role=f.original_role where company_id=f.company_id and user_id=f.user_id;
  perform set_config('makeracc.p6d_certificate_result',jsonb_build_object('draft_no_gl',true,'exact_bigint',true,'server_calculation',true,'vat_retention_recovery_deduction_payable',true,'balanced_dimensioned_no_treasury_journal',true,'roles_rls_tenant',true,'active_completed_closed_inactive_lifecycle',true,'revised_cap',true,'approval_replay',true,'payment_release_guards',true,'exact_reversal_replay',true)::text,true);
end;
$$;
set constraints all immediate;
select current_setting('makeracc.p6d_certificate_result')::jsonb result;
rollback;
