-- MakerACC-Development only. Existing synthetic masters/actor; every change rolls back.
begin;
do $$
declare
 f record; other record; d1 record; d2 record; d3 record; c1 record; c2 record; c3 record;
 rel1 record; rel2 record; rel3 record; pay1 record; replay1 record; pay2 record; reversed record; reverse_replay record;
 original_role public.company_role; original_project_status public.project_status; original_subcontract_status public.subcontract_status; original_party_status public.account_status;
 previous_work bigint; other_previous_work bigint; r1 bigint; r2 bigint; r3 bigint; a1 bigint; a2 bigint; total1 bigint; foreign_company uuid; test_role public.company_role;
 pay_key uuid:=gen_random_uuid(); reverse_key uuid:=gen_random_uuid();
begin
 select m.user_id,m.role,c.id company_id,s.id subcontract_id,s.project_id,s.subcontractor_id,t.id treasury_id,pr.status project_status,s.status subcontract_status,p.status party_status
 into f from public.company_memberships m join public.profiles pf on pf.user_id=m.user_id and pf.status='ACTIVE'
 join public.companies c on c.id=m.company_id and c.status='ACTIVE'
 join public.subcontracts s on s.company_id=c.id and s.status='ACTIVE' and s.retention_bps between 1 and 5000
 join public.projects pr on pr.company_id=c.id and pr.id=s.project_id and pr.status<>'CLOSED'
 join public.parties p on p.company_id=c.id and p.id=s.subcontractor_id and p.type='SUBCONTRACTOR'
 join public.treasury_accounts t on t.company_id=c.id and t.status='ACTIVE' and (t.project_id is null or t.project_id=s.project_id)
 join public.accounts ta on ta.company_id=c.id and ta.id=t.gl_account_id and ta.status='ACTIVE' and ta.account_type='ASSET'
 where m.status='ACTIVE' and exists(select 1 from public.accounts a where a.company_id=c.id and a.status='ACTIVE' and a.system_key in ('PROJECT_COST_SUBCONTRACTORS','SUBCONTRACTOR_RETENTION_PAYABLE','SUBCONTRACTOR_PAYABLE') group by a.company_id having count(distinct a.system_key)=3)
 and (s.original_contract_value_minor::numeric+s.approved_variations_minor::numeric-coalesce((select sum(sc.gross_certified_minor) from public.subcontractor_certificates sc where sc.company_id=c.id and sc.subcontract_id=s.id and sc.status='POSTED'),0))>=3000
 and exists(select 1 from public.subcontracts sx where sx.company_id=c.id and sx.id<>s.id and sx.status='ACTIVE' and sx.retention_bps between 1 and 5000 and (sx.original_contract_value_minor::numeric+sx.approved_variations_minor::numeric-coalesce((select sum(sc.gross_certified_minor) from public.subcontractor_certificates sc where sc.company_id=c.id and sc.subcontract_id=sx.id and sc.status='POSTED'),0))>=1000)
 order by c.id,m.user_id,s.id,t.id limit 1;
 if f.user_id is null then raise exception 'No synthetic Retention Payment fixture'; end if;
 select s.id subcontract_id,s.project_id,s.subcontractor_id into other from public.subcontracts s where s.company_id=f.company_id and s.id<>f.subcontract_id and s.status='ACTIVE' and s.retention_bps between 1 and 5000 and (s.original_contract_value_minor::numeric+s.approved_variations_minor::numeric-coalesce((select sum(sc.gross_certified_minor) from public.subcontractor_certificates sc where sc.company_id=f.company_id and sc.subcontract_id=s.id and sc.status='POSTED'),0))>=1000 order by s.id limit 1;
 original_role:=f.role;original_project_status:=f.project_status;original_subcontract_status:=f.subcontract_status;original_party_status:=f.party_status;
 select coalesce(max(work_value_to_date_minor),0) into previous_work from public.subcontractor_certificates where company_id=f.company_id and subcontract_id=f.subcontract_id and status='POSTED';
 select coalesce(max(work_value_to_date_minor),0) into other_previous_work from public.subcontractor_certificates where company_id=f.company_id and subcontract_id=other.subcontract_id and status='POSTED';
 update public.company_memberships set role='ACCOUNTING_ADMIN' where company_id=f.company_id and user_id=f.user_id;perform set_config('request.jwt.claim.sub',f.user_id::text,true);set local role authenticated;
 select * into d1 from public.create_subcontractor_certificate_draft(f.company_id,current_date,f.subcontract_id,'P6D-RPAY-1-'||gen_random_uuid(),previous_work+1000,0,0,'ZERO',null,false,null,null,'[]',null);select * into c1 from public.approve_post_subcontractor_certificate(f.company_id,d1.subcontractor_certificate_id,gen_random_uuid());
 select * into d2 from public.create_subcontractor_certificate_draft(f.company_id,current_date,f.subcontract_id,'P6D-RPAY-2-'||gen_random_uuid(),previous_work+2000,0,0,'ZERO',null,false,null,null,'[]',null);select * into c2 from public.approve_post_subcontractor_certificate(f.company_id,d2.subcontractor_certificate_id,gen_random_uuid());
 select * into d3 from public.create_subcontractor_certificate_draft(f.company_id,current_date,other.subcontract_id,'P6D-RPAY-X-'||gen_random_uuid(),other_previous_work+1000,0,0,'ZERO',null,false,null,null,'[]',null);select * into c3 from public.approve_post_subcontractor_certificate(f.company_id,d3.subcontractor_certificate_id,gen_random_uuid());
 select retention_amount_minor into r1 from public.subcontractor_certificates where id=d1.subcontractor_certificate_id;select retention_amount_minor into r2 from public.subcontractor_certificates where id=d2.subcontractor_certificate_id;select retention_amount_minor into r3 from public.subcontractor_certificates where id=d3.subcontractor_certificate_id;
 select * into rel1 from public.post_subcontractor_retention_release(f.company_id,current_date,f.subcontract_id,r1,null,'payment source 1',jsonb_build_array(jsonb_build_object('certificate_id',d1.subcontractor_certificate_id,'amount_minor',r1)),gen_random_uuid());
 select * into rel2 from public.post_subcontractor_retention_release(f.company_id,current_date,f.subcontract_id,r2,null,'payment source 2',jsonb_build_array(jsonb_build_object('certificate_id',d2.subcontractor_certificate_id,'amount_minor',r2)),gen_random_uuid());
 select * into rel3 from public.post_subcontractor_retention_release(f.company_id,current_date,other.subcontract_id,r3,null,'cross source',jsonb_build_array(jsonb_build_object('certificate_id',d3.subcontractor_certificate_id,'amount_minor',r3)),gen_random_uuid());reset role;
 if least(r1,r2,r3)<2 then raise exception 'Retention Payment fixture too small';end if;a1:=greatest(1,r1/2);a2:=greatest(1,r2/2);total1:=a1+a2;
 -- Active Treasury required; existing released liabilities remain payable after master closure/inactivation.
 update public.treasury_accounts set status='INACTIVE' where id=f.treasury_id;set local role authenticated;begin perform public.post_subcontractor_retention_payment(f.company_id,current_date,f.subcontract_id,f.treasury_id,1,'TRANSFER',null,null,jsonb_build_array(jsonb_build_object('release_id',rel1.retention_release_id,'amount_minor',1)),gen_random_uuid());raise exception 'Inactive Treasury allowed';exception when check_violation then null;end;reset role;update public.treasury_accounts set status='ACTIVE' where id=f.treasury_id;
 update public.projects set status='CLOSED' where id=f.project_id;update public.subcontracts set status='CLOSED' where id=f.subcontract_id;update public.parties set status='INACTIVE' where id=f.subcontractor_id;
 update public.company_memberships set role='ACCOUNTANT' where company_id=f.company_id and user_id=f.user_id;set local role authenticated;
 select * into pay1 from public.post_subcontractor_retention_payment(f.company_id,current_date,f.subcontract_id,f.treasury_id,total1,'TRANSFER',' P6D-RPAY ',' partial multi ',jsonb_build_array(jsonb_build_object('release_id',rel1.retention_release_id,'amount_minor',a1),jsonb_build_object('release_id',rel2.retention_release_id,'amount_minor',a2)),pay_key);
 select * into replay1 from public.post_subcontractor_retention_payment(f.company_id,current_date,f.subcontract_id,f.treasury_id,total1,'TRANSFER','P6D-RPAY','partial multi',jsonb_build_array(jsonb_build_object('release_id',rel2.retention_release_id,'amount_minor',a2),jsonb_build_object('release_id',rel1.retention_release_id,'amount_minor',a1)),pay_key);reset role;
 if pay1.replayed or not replay1.replayed or pay1.retention_payment_id<>replay1.retention_payment_id or pay1.journal_entry_id<>replay1.journal_entry_id then raise exception 'Retention Payment replay mismatch';end if;
 if not exists(select 1 from public.subcontractor_retention_payments p where p.id=pay1.retention_payment_id and p.project_id=f.project_id and p.subcontractor_id=f.subcontractor_id and p.subcontract_id=f.subcontract_id and p.treasury_account_id=f.treasury_id and p.total_amount_minor=total1 and p.status='POSTED') or (select count(*) from public.subcontractor_retention_payment_allocations where retention_payment_id=pay1.retention_payment_id)<>2 then raise exception 'Retention Payment document mismatch';end if;
 if (select count(*) from public.journal_lines where journal_entry_id=pay1.journal_entry_id)<>2 or (select sum(debit_minor-credit_minor) from public.journal_lines where journal_entry_id=pay1.journal_entry_id)<>0
 or not exists(select 1 from public.journal_lines l join public.accounts a on a.id=l.account_id where l.journal_entry_id=pay1.journal_entry_id and a.system_key='SUBCONTRACTOR_PAYABLE' and l.debit_minor=total1 and l.project_id=f.project_id and l.party_id=f.subcontractor_id and l.subcontract_id=f.subcontract_id)
 or not exists(select 1 from public.journal_lines l where l.journal_entry_id=pay1.journal_entry_id and l.credit_minor=total1 and l.treasury_account_id=f.treasury_id and l.project_id=f.project_id and l.subcontract_id=f.subcontract_id)
 or exists(select 1 from public.journal_lines l join public.accounts a on a.id=l.account_id where l.journal_entry_id=pay1.journal_entry_id and a.system_key in ('SUBCONTRACTOR_RETENTION_PAYABLE','PROJECT_COST_SUBCONTRACTORS','INPUT_VAT','SUBCONTRACTOR_ADVANCE')) then raise exception 'Retention Payment journal mismatch';end if;
 -- Full remainder, overpayment/cross-contract rejection, and Release reversal dependency.
 update public.company_memberships set role='ACCOUNTING_ADMIN' where company_id=f.company_id and user_id=f.user_id;set local role authenticated;
 select * into pay2 from public.post_subcontractor_retention_payment(f.company_id,current_date,f.subcontract_id,f.treasury_id,r1-a1,'CHEQUE',null,'full remainder',jsonb_build_array(jsonb_build_object('release_id',rel1.retention_release_id,'amount_minor',r1-a1)),gen_random_uuid());
 begin perform public.post_subcontractor_retention_payment(f.company_id,current_date,f.subcontract_id,f.treasury_id,r2-a2+1,'TRANSFER',null,null,jsonb_build_array(jsonb_build_object('release_id',rel2.retention_release_id,'amount_minor',r2-a2+1)),gen_random_uuid());raise exception 'Overpayment allowed';exception when check_violation then null;end;
 begin perform public.post_subcontractor_retention_payment(f.company_id,current_date,f.subcontract_id,f.treasury_id,1,'TRANSFER',null,null,jsonb_build_array(jsonb_build_object('release_id',rel3.retention_release_id,'amount_minor',1)),gen_random_uuid());raise exception 'Cross-Subcontract payment allowed';exception when check_violation then null;end;
 begin perform public.reverse_subcontractor_retention_release(f.company_id,rel1.retention_release_id,current_date,'blocked',gen_random_uuid());raise exception 'Live Retention Payment did not block Release reversal';exception when check_violation then null;end;reset role;
 if (select r.total_amount_minor-coalesce(sum(a.allocated_amount_minor) filter(where p.status='POSTED'),0) from public.subcontractor_retention_releases r left join public.subcontractor_retention_payment_allocations a on a.retention_release_id=r.id left join public.subcontractor_retention_payments p on p.id=a.retention_payment_id where r.id=rel1.retention_release_id group by r.total_amount_minor)<>0 then raise exception 'Authoritative released-but-unpaid mismatch';end if;
 -- RLS and command authorization matrix.
 foreach test_role in array enum_range(null::public.company_role) loop update public.company_memberships set role=test_role where company_id=f.company_id and user_id=f.user_id;set local role authenticated;
  if test_role in ('ACCOUNTING_ADMIN','ACCOUNTANT','MANAGEMENT_VIEWER') then if not exists(select 1 from public.subcontractor_retention_payments where id=pay1.retention_payment_id) then raise exception 'Allowed read failed: %',test_role;end if;elsif exists(select 1 from public.subcontractor_retention_payments where id=pay1.retention_payment_id) then raise exception 'Denied read: %',test_role;end if;
  if test_role not in ('ACCOUNTING_ADMIN','ACCOUNTANT') then begin perform public.post_subcontractor_retention_payment(f.company_id,current_date,f.subcontract_id,f.treasury_id,1,'TRANSFER',null,null,jsonb_build_array(jsonb_build_object('release_id',rel2.retention_release_id,'amount_minor',1)),gen_random_uuid());raise exception 'Denied post: %',test_role;exception when insufficient_privilege then null;end;end if;
  if test_role<>'ACCOUNTING_ADMIN' then begin perform public.reverse_subcontractor_retention_payment(f.company_id,pay2.retention_payment_id,current_date,'denied',gen_random_uuid());raise exception 'Denied reversal: %',test_role;exception when insufficient_privilege then null;end;end if;reset role;
 end loop;
 update public.company_memberships set role='ACCOUNTING_ADMIN',status='INACTIVE' where company_id=f.company_id and user_id=f.user_id;set local role authenticated;begin perform public.post_subcontractor_retention_payment(f.company_id,current_date,f.subcontract_id,f.treasury_id,1,'TRANSFER',null,null,jsonb_build_array(jsonb_build_object('release_id',rel2.retention_release_id,'amount_minor',1)),gen_random_uuid());raise exception 'Inactive member posted';exception when insufficient_privilege then null;end;reset role;update public.company_memberships set status='ACTIVE' where company_id=f.company_id and user_id=f.user_id;
 select c.id into foreign_company from public.companies c where c.id<>f.company_id and not exists(select 1 from public.company_memberships m where m.company_id=c.id and m.user_id=f.user_id and m.status='ACTIVE') limit 1;set local role authenticated;begin perform public.post_subcontractor_retention_payment(foreign_company,current_date,f.subcontract_id,f.treasury_id,1,'TRANSFER',null,null,jsonb_build_array(jsonb_build_object('release_id',rel2.retention_release_id,'amount_minor',1)),gen_random_uuid());raise exception 'Cross-tenant payment';exception when insufficient_privilege then null;end;reset role;
 -- Exact reversal restores availability; after all consuming payments reverse, Release reversal is eligible.
 update public.company_memberships set role='ACCOUNTING_ADMIN' where company_id=f.company_id and user_id=f.user_id;set local role authenticated;select * into reversed from public.reverse_subcontractor_retention_payment(f.company_id,pay2.retention_payment_id,current_date,'restore availability',reverse_key);select * into reverse_replay from public.reverse_subcontractor_retention_payment(f.company_id,pay2.retention_payment_id,current_date,'restore availability',reverse_key);reset role;
 if reversed.replayed or not reverse_replay.replayed or reversed.reversal_journal_entry_id<>reverse_replay.reversal_journal_entry_id then raise exception 'Retention Payment reversal replay mismatch';end if;
 if exists(select 1 from public.journal_lines o full join public.journal_lines r on r.journal_entry_id=reversed.reversal_journal_entry_id and r.line_number=o.line_number where o.journal_entry_id=pay2.journal_entry_id and (r.account_id<>o.account_id or r.debit_minor<>o.credit_minor or r.credit_minor<>o.debit_minor or r.project_id is distinct from o.project_id or r.party_id is distinct from o.party_id or r.subcontract_id is distinct from o.subcontract_id or r.treasury_account_id is distinct from o.treasury_account_id)) then raise exception 'Retention Payment reversal not exact';end if;
 if (select r.total_amount_minor-coalesce(sum(a.allocated_amount_minor) filter(where p.status='POSTED'),0) from public.subcontractor_retention_releases r left join public.subcontractor_retention_payment_allocations a on a.retention_release_id=r.id left join public.subcontractor_retention_payments p on p.id=a.retention_payment_id where r.id=rel1.retention_release_id group by r.total_amount_minor)<>r1-a1 then raise exception 'Reversal did not restore availability';end if;
 set local role authenticated;perform public.reverse_subcontractor_retention_payment(f.company_id,pay1.retention_payment_id,current_date,'remove dependency',gen_random_uuid());perform public.reverse_subcontractor_retention_release(f.company_id,rel1.retention_release_id,current_date,'dependency removed',gen_random_uuid());reset role;
 update public.projects set status=original_project_status where id=f.project_id;update public.subcontracts set status=original_subcontract_status where id=f.subcontract_id;update public.parties set status=original_party_status where id=f.subcontractor_id;update public.company_memberships set role=original_role where company_id=f.company_id and user_id=f.user_id;
 perform set_config('makeracc.p6d_retention_payment_result',jsonb_build_object('partial_full_multi',true,'same_subcontract',true,'authoritative_availability',true,'active_treasury',true,'closed_inactive_settlement',true,'roles_rls_tenant',true,'payable_treasury_only',true,'no_reposting',true,'idempotency',true,'release_guard',true,'exact_reversal_restore',true)::text,true);
end $$;
set constraints all immediate;
select current_setting('makeracc.p6d_retention_payment_result')::jsonb result;
rollback;
