import {sourceClient} from '../historical/useHistoricalSources';
import {moneyCell,type FinancialReport} from './reportExport';
type Entry={id:string;company_id:string;journal_reference:string;posting_date:string;description:string;source_type:string;source_id:string;posting_purpose:string;reversal_of_journal_entry_id:string|null};
type Line={id:string;company_id:string;journal_entry_id:string;line_number:number;account_id:string;debit_minor:string;credit_minor:string;project_id:string|null;treasury_account_id:string|null;party_id:string|null};
export async function postedJournalReport(companyId:string,company:string,locale:'en'|'ar'):Promise<FinancialReport>{
 const client=sourceClient();
 async function read<T extends {company_id:string}>(table:string,columns:string):Promise<T[]>{const rows:T[]=[];for(let offset=0;;offset+=500){const {data,error}=await client.from(table).select(columns).eq('company_id',companyId).order('id').range(offset,offset+499);if(error||!data)throw Error('Posted accounting could not be read.');const batch=data as unknown as T[];if(batch.some(r=>r.company_id!==companyId))throw Error('Company scope changed.');rows.push(...batch);if(batch.length<500)return rows;}}
 const entries=await read<Entry>('journal_entries','id,company_id,journal_reference,posting_date,description,source_type,source_id,posting_purpose,reversal_of_journal_entry_id');
 const lines=await read<Line>('journal_lines','id,company_id,journal_entry_id,line_number,account_id,debit_minor::text,credit_minor::text,project_id,treasury_account_id,party_id');
 const byEntry=new Map(entries.map(e=>[e.id,e]));if(lines.some(l=>!byEntry.has(l.journal_entry_id)))throw Error('Journal visibility changed. Refresh before exporting.');
 const sums=new Map<string,{debit:bigint;credit:bigint}>();for(const l of lines){const s=sums.get(l.journal_entry_id)??{debit:0n,credit:0n};s.debit+=BigInt(l.debit_minor);s.credit+=BigInt(l.credit_minor);sums.set(l.journal_entry_id,s);}
 if(entries.some(e=>!sums.has(e.id)||sums.get(e.id)!.debit!==sums.get(e.id)!.credit))throw Error('Journal lines are incomplete or unbalanced. Refresh before exporting.');
 const debit=lines.reduce((n,l)=>n+BigInt(l.debit_minor),0n).toString(),credit=lines.reduce((n,l)=>n+BigInt(l.credit_minor),0n).toString(),ar=locale==='ar';
 return {company,locale,title:ar?'المعاملات المحاسبية المرحلة':'Posted Accounting Transactions',period:ar?'كل الفترات المصرح بها':'All authorized accounting periods',generated:new Date().toISOString(),filename:'MakerACC-Posted-Accounting-'+new Date().toISOString().slice(0,10),note:ar?'قيود محاسبية فعلية، بما فيها قيود العكس. إجمالي المدين والدائن ليس إجمالي المصروفات أو الصرف النقدي. نطاق الشركة وصلاحيات قاعدة البيانات، بما فيها خصوصية الرواتب، مطبقة.':'Canonical journals, including reversals. Debit/credit turnover is not Expense cost or historical cash outflow. Company RLS and Payroll privacy determine visible records.',sections:[{title:ar?'إجمالي حركة القيود':'Journal turnover',headers:ar?['عدد القيود','المدين (درهم)','الدائن (درهم)']:['Journal count','Debit AED','Credit AED'],rows:[[entries.length,moneyCell(debit),moneyCell(credit)]]},{title:ar?'القيود':'Journals',headers:ar?['المرجع','التاريخ','الوصف','نوع المصدر','المصدر','الغرض','عكس قيد','المدين','الدائن']:['Reference','Date','Description','Source type','Source ID','Purpose','Reversal of','Debit AED','Credit AED'],rows:entries.map(e=>[e.journal_reference,e.posting_date,e.description,e.source_type,e.source_id,e.posting_purpose,e.reversal_of_journal_entry_id,moneyCell(sums.get(e.id)!.debit.toString()),moneyCell(sums.get(e.id)!.credit.toString())])},{title:ar?'سطور القيد':'Journal lines',headers:ar?['مرجع القيد','السطر','الحساب','المدين','الدائن','المشروع','الخزينة','الطرف']:['Journal reference','Line','Account ID','Debit AED','Credit AED','Project ID','Treasury ID','Party ID'],rows:lines.map(l=>[byEntry.get(l.journal_entry_id)!.journal_reference,l.line_number,l.account_id,moneyCell(l.debit_minor),moneyCell(l.credit_minor),l.project_id,l.treasury_account_id,l.party_id])}]};
}
