import type {SourceRecord,ReportingBasis} from '../historical/sourceModel';
import {sourceValue,sourceCurrentAmount,sourceOriginalAmount,sourceDirection,sourceAccounting,sourceReportingMonth,sourceTotals,decimalMinor} from '../historical/sourceModel';
import type {DashboardSummary} from '../dashboard/dashboardSummary';
import {moneyCell,type FinancialReport,type ReportSection,type ReportCell} from './reportExport';
const salary=(v:string):ReportCell=>{try{return moneyCell(decimalMinor(v));}catch{return v||null;}};
export function sourceReport(rows:SourceRecord[],company:string,locale:'en'|'ar',basis:ReportingBasis,kind:'GENERAL'|'PAYROLL'|'OVERVIEW',period:string,posted?:DashboardSummary|null):FinancialReport {
 const ar=locale==='ar',t=sourceTotals(rows),sections:ReportSection[]=[];const pair=(label:string,a:string,b:string):ReportCell[]=>[label,moneyCell(a),moneyCell(b)];
 const note=ar?'مبالغ المصدر التاريخية منفصلة عن المحاسبة المرحلة. كل أساس مالي مستقل؛ لا تجمع الرواتب أو الوارد أو الفواتير مع الصرف. الأصل محفوظ والمصحح النشط يستبعد المؤرشف.':'Historical sources are separate from posted accounting. Each basis stands alone: do not add Payroll, inflows or invoice-only amounts to cash outflows. Original evidence is preserved; corrected active figures exclude archived records.';
 sections.push({title:ar?'إجماليات المصدر حسب التصفية':'Source totals · selected filters',headers:ar?['الأساس','الأصلي (درهم)','المصحح النشط (درهم)']:['Basis','Original AED','Corrected active AED'],rows:[pair(ar?'الصرف النقدي':'Cash outflows',t.originalOut,t.correctedOut),pair(ar?'الوارد النقدي':'Cash inflows',t.originalIn,t.correctedIn),pair(ar?'فواتير فقط':'Invoice-only amounts',t.originalInvoice,t.correctedInvoice),pair(ar?'صافي رواتب المصدر':'Source Payroll net',t.originalPayroll,t.correctedPayroll)]});
 if(kind==='OVERVIEW'){
  const months=[...new Set(rows.map(r=>sourceReportingMonth(r,basis)))].sort();
  sections.push({title:ar?'النشاط الشهري':'Monthly historical activity',headers:ar?['الشهر','سجلات مالية','سجلات رواتب','صرف أصلي','صرف نشط','وارد أصلي','صافي رواتب أصلي','صافي رواتب نشط']:['Month','General records','Payroll records','Original outflow AED','Active outflow AED','Original inflow AED','Original Payroll AED','Active Payroll AED'],rows:months.map(m=>{const s=sourceTotals(rows.filter(r=>sourceReportingMonth(r,basis)===m));return [m,s.general,s.payroll,moneyCell(s.originalOut),moneyCell(s.correctedOut),moneyCell(s.originalIn),moneyCell(s.originalPayroll),moneyCell(s.correctedPayroll)];})});
  const groups=new Map<string,bigint>();for(const r of rows.filter(r=>r.record_type==='GENERAL'&&sourceDirection(r)==='OUT'&&r.review_status!=='CANCELLED')){const category=sourceValue(r,'category',r.classification.category_proposal)||'Unclassified';groups.set(category,(groups.get(category)??0n)+BigInt(sourceCurrentAmount(r)??'0'));}
  sections.push({title:ar?'توزيع الصرف النشط حسب فئة المراجعة':'Active cash outflow by review category',headers:ar?['الفئة','المبلغ (درهم)']:['Category','Amount AED'],rows:[...groups].map(([name,minor])=>[name,moneyCell(minor.toString())])});
  sections.push({title:ar?'الحسابات المرحلة — أساس مستقل':'Posted Accounting — separate basis',headers:ar?['المؤشر','القيمة']:['Metric','Value'],rows:posted?[[ar?'المشاريع النشطة':'Active Projects',posted.activeProjects],[ar?'صافي المصروفات المرحلة':'Posted Expense net AED',moneyCell(posted.postedExpenseNet)],[ar?'مستحقات الموردين':'Supplier outstanding AED',moneyCell(posted.supplierOutstanding)],[ar?'مستحقات المقاولين':'Subcontractor outstanding AED',moneyCell(posted.subcontractorOutstanding)],[ar?'الاحتجاز':'Retention held AED',moneyCell(posted.retentionHeld)]]:[[ar?'الحالة':'State',ar?'لم تتوفر بيانات المحاسبة المرحلة؛ هذا تقرير مصادر فقط':'Posted accounting read unavailable; this is a source report only.']]});
 }else if(kind==='PAYROLL')sections.push({title:ar?'سجل رواتب المصدر (ليس مسير رواتب مرحل)':'Source Payroll register (not posted Payroll)',headers:ar?['المعرف','الموظف','شهر التقرير','الراتب الأساسي','عمل / غياب','إضافات','خصومات','الصافي الأصلي','الصافي المصحح','حالة المحاسبة','حالة المراجعة']:['Employee ID','Employee name','Reporting month','Basic salary AED','Working / absence days','Additions AED','Deductions AED','Original net AED','Corrected net AED','Accounting status','Review status'],rows:rows.map(r=>[sourceValue(r,'employee_id',r.raw_source['Payroll ID']),sourceValue(r,'description',r.description),sourceReportingMonth(r,basis),salary(sourceValue(r,'basic_salary',r.raw_source['Monthly Salary'])),sourceValue(r,'working_days',r.raw_source['Days Worked'])+' / '+sourceValue(r,'absence_days',r.raw_source['Absence/Deduction Days']),salary(sourceValue(r,'additions',r.raw_source['Addition Amount'])),salary(sourceValue(r,'deductions',r.raw_source['Other Deduction'])),moneyCell(r.payroll_net_minor??'0'),sourceCurrentAmount(r)===null?null:moneyCell(sourceCurrentAmount(r)!),sourceAccounting(r),r.review_status])});
 else sections.push({title:ar?'الحركات المالية التاريخية':'Historical financial transactions',headers:ar?['المرجع','التاريخ','الوصف','الفئة','نوع المعاملة','أصلي (درهم)','مصحح (درهم)','اتجاه النقد','الدفع','المحاسبة','الخزينة','الطرف','المشروع','مرجع القيد']:['Reference','Date','Description','Category','Transaction type','Original AED','Corrected AED','Cash direction','Payment status','Accounting status','Treasury','Party','Project','Journal reference'],rows:rows.map(r=>[r.source_reference,sourceValue(r,'date',r.source_date),sourceValue(r,'description',r.description),sourceValue(r,'category',r.classification.category_proposal),sourceValue(r,'nature',r.classification.nature),sourceOriginalAmount(r)===null?null:moneyCell(sourceOriginalAmount(r)!),sourceCurrentAmount(r)===null?null:moneyCell(sourceCurrentAmount(r)!),sourceDirection(r),r.cash_treasury_id?(sourceDirection(r)==='OUT'?'PAID':sourceDirection(r)==='IN'?'RECEIVED':'NO CASH MOVEMENT'):'NO CASH MOVEMENT',sourceAccounting(r),r.cash_treasury?.code??'',sourceValue(r,'party',r.raw_source['Supplier (exact)']),sourceValue(r,'project',r.classification.project_decision),r.expense?.posted_journal_entry_id??''])});
 const title=kind==='OVERVIEW'?(ar?'الملخص المالي التنفيذي':'Executive Financial Summary'):kind==='PAYROLL'?(ar?'سجل رواتب المصدر':'Historical Payroll Register'):(ar?'المصروفات والحركات المالية':'Expenses & Financial Transactions');
 return {company,title,period:period+' · '+(basis==='SOURCE'?(ar?'شهر المصدر':'Source month basis'):(ar?'شهر تاريخ المعاملة / الراتب':'Transaction date / salary month basis')),locale,generated:new Date().toISOString(),note,sections,filename:'MakerACC-'+kind+'-'+new Date().toISOString().slice(0,10)};
}
