import {useEffect,useState} from 'react';
import {useProductionMasterData} from '../master/productionMasterDataContext';
import {useI18n} from '../i18n/I18nContext';
import {sourceClient} from '../historical/useHistoricalSources';
import {minorDisplay} from '../historical/sourceModel';
type Line={company_id:string;journal_entry_id:string;line_number:number;account_id:string;debit_minor:string;credit_minor:string};
export function ExpenseJournal({companyId,journalId}:{companyId:string;journalId:string}){
 const {locale}=useI18n(),ar=locale==='ar',master=useProductionMasterData();
 const accountLabel=(id:string)=>{const a=master.phase==='READY'?master.accounts?.find(a=>a.companyId===companyId&&a.id===id):undefined;return a?a.code+' · '+a.name:id;};const [lines,setLines]=useState<Line[]>([]),[error,setError]=useState(false),[revision,setRevision]=useState(0);
 useEffect(()=>{let live=true;setLines([]);setError(false);void sourceClient().from('journal_lines').select('company_id,journal_entry_id,line_number,account_id,debit_minor::text,credit_minor::text').eq('company_id',companyId).eq('journal_entry_id',journalId).order('line_number').then(({data,error})=>{if(!live)return;const rows=(data??[]) as unknown as Line[];try{if(error||rows.length<2||rows.some(r=>r.company_id!==companyId||r.journal_entry_id!==journalId||!/^\d+$/.test(r.debit_minor)||!/^\d+$/.test(r.credit_minor))||rows.reduce((n,r)=>n+BigInt(r.debit_minor)-BigInt(r.credit_minor),0n)!==0n)throw Error('read');setLines(rows);}catch{setError(true);}});return()=>{live=false;};},[companyId,journalId,revision]);
 return <details className="rounded-xl border p-4"><summary className="cursor-pointer font-semibold">{ar?'عرض القيد المحاسبي':'View accounting journal'}</summary><p className="my-3 break-all text-xs"><bdi>{journalId}</bdi></p>{error?<div role="alert">{ar?'تعذر تحميل القيد الكامل.':'Complete journal could not be loaded.'}<button type="button" className="ml-3 underline" onClick={()=>setRevision(n=>n+1)}>{ar?'إعادة المحاولة':'Retry'}</button></div>:lines.length?<div className="overflow-x-auto"><table className="w-full text-start text-sm"><thead><tr>{(ar?['حساب GL','مدين (درهم)','دائن (درهم)']:['GL account','Debit AED','Credit AED']).map(h=><th key={h} className="p-2 text-start">{h}</th>)}</tr></thead><tbody>{lines.map(l=><tr key={l.line_number}><td className="break-all p-2"><bdi>{accountLabel(l.account_id)}</bdi></td><td className="p-2"><bdi dir="ltr">{minorDisplay(l.debit_minor)}</bdi></td><td className="p-2"><bdi dir="ltr">{minorDisplay(l.credit_minor)}</bdi></td></tr>)}</tbody></table><p>{ar?'قيد متوازن':'Balanced journal'}</p></div>:<p role="status">{ar?'جار تحميل القيد':'Loading journal…'}</p>}</details>;
}
