import type{SupabaseClient}from"@supabase/supabase-js";import type{Database}from"../types/database.generated";
export interface RetentionPaymentAllocationInput{releaseId:string;amountMinor:string}export interface RetentionPaymentInput{date:string;subcontractId:string;treasuryId:string;totalMinor:string;method:Database["public"]["Enums"]["payment_method"];externalReference:string|null;notes:string|null;allocations:RetentionPaymentAllocationInput[]}export interface RetentionPaymentReceipt{retention_payment_id:string;payment_reference:string;journal_entry_id:string;replayed:boolean}
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i,money=(v:unknown)=>typeof v==="string"&&/^\d+$/.test(v)&&BigInt(v)>=1n&&BigInt(v)<=9000000000000000n;export const canPostRetentionPayment=(role:string)=>role==="ACCOUNTING_ADMIN"||role==="ACCOUNTANT";
export function parseRetentionPaymentAED(value:string){if(!/^\d+(\.\d{1,2})?$/.test(value.trim()))throw new Error("invalid");const[w,f=""]=value.trim().split("."),minor=BigInt(w)*100n+BigInt(f.padEnd(2,"0"));if(minor<1n||minor>9000000000000000n)throw new Error("invalid");return minor.toString()}
export function normalizeRetentionPaymentInput(input:RetentionPaymentInput):RetentionPaymentInput{if(!input||!/^\d{4}-\d{2}-\d{2}$/.test(input.date)||!Number.isFinite(Date.parse(input.date))||new Date(input.date).toISOString().slice(0,10)!==input.date||!uuid.test(input.subcontractId)||!uuid.test(input.treasuryId)||!money(input.totalMinor)||!["CASH","BANK","TRANSFER","CHEQUE","OTHER"].includes(input.method)||!Array.isArray(input.allocations)||input.allocations.length<1||input.allocations.length>999)throw new Error("invalid");const externalReference=input.externalReference?.trim()||null,notes=input.notes?.trim()||null;if(externalReference&&[...externalReference].length>200||notes&&[...notes].length>2000)throw new Error("invalid");const allocations=input.allocations.map(row=>{if(!uuid.test(row.releaseId)||!money(row.amountMinor))throw new Error("invalid");return{releaseId:row.releaseId,amountMinor:BigInt(row.amountMinor).toString()}}).sort((a,b)=>a.releaseId.localeCompare(b.releaseId));if(new Set(allocations.map(row=>row.releaseId)).size!==allocations.length||allocations.reduce((sum,row)=>sum+BigInt(row.amountMinor),0n)!==BigInt(input.totalMinor))throw new Error("invalid");return{date:input.date,subcontractId:input.subcontractId,treasuryId:input.treasuryId,totalMinor:BigInt(input.totalMinor).toString(),method:input.method,externalReference,notes,allocations}}
export function retentionPaymentPayload(companyId:string,key:string,raw:RetentionPaymentInput){if(!uuid.test(companyId)||!uuid.test(key))throw new Error("invalid");const i=normalizeRetentionPaymentInput(raw);return{target_company_id:companyId,target_payment_date:i.date,target_subcontract_id:i.subcontractId,target_treasury_account_id:i.treasuryId,target_total_amount_minor:i.totalMinor,target_payment_method:i.method,target_external_reference:i.externalReference,target_notes:i.notes,target_allocations:i.allocations.map(row=>({release_id:row.releaseId,amount_minor:row.amountMinor})),target_idempotency_key:key}}
type PostDatabase=Omit<Database,"public">&{public:Omit<Database["public"],"Functions">&{Functions:Omit<Database["public"]["Functions"],"post_subcontractor_retention_payment">&{post_subcontractor_retention_payment:{Args:ReturnType<typeof retentionPaymentPayload>;Returns:RetentionPaymentReceipt[]}}}};
export function validRetentionPaymentReceipt(value:unknown):value is RetentionPaymentReceipt{if(!value||typeof value!=="object")return false;const row=value as RetentionPaymentReceipt;return uuid.test(row.retention_payment_id)&&uuid.test(row.journal_entry_id)&&typeof row.payment_reference==="string"&&!!row.payment_reference&&typeof row.replayed==="boolean"}export class RetentionPaymentPostError extends Error{readonly rejected:boolean;constructor(rejected:boolean){super("unresolved");this.rejected=rejected}}
export async function postRetentionPayment(client:SupabaseClient<Database>,companyId:string,key:string,input:RetentionPaymentInput):Promise<RetentionPaymentReceipt>{const{data,error}=await(client as unknown as SupabaseClient<PostDatabase>).rpc("post_subcontractor_retention_payment",retentionPaymentPayload(companyId,key,input));if(error)throw new RetentionPaymentPostError(true);if(!data||data.length!==1||!validRetentionPaymentReceipt(data[0]))throw new RetentionPaymentPostError(false);return data[0]}
