import type{SupabaseClient}from"@supabase/supabase-js";import type{Database}from"../types/database.generated";
export interface RetentionReleaseAllocationInput{certificateId:string;amountMinor:string}export interface RetentionReleaseInput{date:string;subcontractId:string;totalMinor:string;authorizationReference:string|null;notes:string|null;allocations:RetentionReleaseAllocationInput[]}export interface RetentionReleaseReceipt{retention_release_id:string;release_reference:string;journal_entry_id:string;replayed:boolean}
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i,money=(v:unknown)=>typeof v==="string"&&/^\d+$/.test(v)&&BigInt(v)>=1n&&BigInt(v)<=9000000000000000n;export const canPostRetentionRelease=(role:string)=>role==="ACCOUNTING_ADMIN";
export function parseRetentionReleaseAED(value:string){if(!/^\d+(\.\d{1,2})?$/.test(value.trim()))throw new Error("invalid");const[w,f=""]=value.trim().split("."),minor=BigInt(w)*100n+BigInt(f.padEnd(2,"0"));if(minor<1n||minor>9000000000000000n)throw new Error("invalid");return minor.toString()}
export function normalizeRetentionReleaseInput(input:RetentionReleaseInput):RetentionReleaseInput{if(!input||!/^\d{4}-\d{2}-\d{2}$/.test(input.date)||!Number.isFinite(Date.parse(input.date))||new Date(input.date).toISOString().slice(0,10)!==input.date||!uuid.test(input.subcontractId)||!money(input.totalMinor)||!Array.isArray(input.allocations)||input.allocations.length<1||input.allocations.length>999)throw new Error("invalid");const authorizationReference=input.authorizationReference?.trim()||null,notes=input.notes?.trim()||null;if(authorizationReference&&[...authorizationReference].length>200||notes&&[...notes].length>2000)throw new Error("invalid");const allocations=input.allocations.map(row=>{if(!uuid.test(row.certificateId)||!money(row.amountMinor))throw new Error("invalid");return{certificateId:row.certificateId,amountMinor:BigInt(row.amountMinor).toString()}}).sort((a,b)=>a.certificateId.localeCompare(b.certificateId));if(new Set(allocations.map(row=>row.certificateId)).size!==allocations.length||allocations.reduce((sum,row)=>sum+BigInt(row.amountMinor),0n)!==BigInt(input.totalMinor))throw new Error("invalid");return{date:input.date,subcontractId:input.subcontractId,totalMinor:BigInt(input.totalMinor).toString(),authorizationReference,notes,allocations}}
export function retentionReleasePayload(companyId:string,key:string,raw:RetentionReleaseInput){if(!uuid.test(companyId)||!uuid.test(key))throw new Error("invalid");const i=normalizeRetentionReleaseInput(raw);return{target_company_id:companyId,target_release_date:i.date,target_subcontract_id:i.subcontractId,target_total_amount_minor:i.totalMinor,target_authorization_reference:i.authorizationReference,target_notes:i.notes,target_allocations:i.allocations.map(row=>({certificate_id:row.certificateId,amount_minor:row.amountMinor})),target_idempotency_key:key}}
type PostDatabase=Omit<Database,"public">&{public:Omit<Database["public"],"Functions">&{Functions:Omit<Database["public"]["Functions"],"post_subcontractor_retention_release">&{post_subcontractor_retention_release:{Args:ReturnType<typeof retentionReleasePayload>;Returns:RetentionReleaseReceipt[]}}}};
export function validRetentionReleaseReceipt(value:unknown):value is RetentionReleaseReceipt{if(!value||typeof value!=="object")return false;const row=value as RetentionReleaseReceipt;return uuid.test(row.retention_release_id)&&uuid.test(row.journal_entry_id)&&typeof row.release_reference==="string"&&!!row.release_reference&&typeof row.replayed==="boolean"}export class RetentionReleasePostError extends Error{readonly rejected:boolean;constructor(rejected:boolean){super("unresolved");this.rejected=rejected}}
export async function postRetentionRelease(client:SupabaseClient<Database>,companyId:string,key:string,input:RetentionReleaseInput):Promise<RetentionReleaseReceipt>{const{data,error}=await(client as unknown as SupabaseClient<PostDatabase>).rpc("post_subcontractor_retention_release",retentionReleasePayload(companyId,key,input));if(error)throw new RetentionReleasePostError(true);if(!data||data.length!==1||!validRetentionReleaseReceipt(data[0]))throw new RetentionReleasePostError(false);return data[0]}
