import type { SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "../types/database.generated";
import { RetentionReleaseReverseError, normalizeRetentionReleaseReverseInput, reverseRetentionRelease, retentionReleaseReversePayload, validRetentionReleaseReverseReceipt, type RetentionReleaseReverseInput, type RetentionReleaseReverseReceipt } from "./retentionReleaseReverseRepository";
export interface RetentionReleaseReverseAttempt { version: 1; userId: string; companyId: string; releaseId: string; key: string; input: RetentionReleaseReverseInput; receipt?: RetentionReleaseReverseReceipt; }
export const retentionReleaseReverseStorageKey = (userId: string, companyId: string, releaseId: string) => `makeracc:retention-release-reverse:${userId}:${companyId}:${releaseId}`;
export function loadRetentionReleaseReverseAttempt(storage: Storage, userId: string, companyId: string, releaseId: string): RetentionReleaseReverseAttempt | null { const text = storage.getItem(retentionReleaseReverseStorageKey(userId, companyId, releaseId)); if (!text) return null; const value = JSON.parse(text) as RetentionReleaseReverseAttempt; if (value.version !== 1 || value.userId !== userId || value.companyId !== companyId || value.releaseId !== releaseId || (value.receipt !== undefined && !validRetentionReleaseReverseReceipt(value.receipt))) throw new Error("recovery"); const input = normalizeRetentionReleaseReverseInput(value.input); retentionReleaseReversePayload(companyId, releaseId, value.key, input); return { version: 1, userId, companyId, releaseId, key: value.key, input, ...(value.receipt ? { receipt: value.receipt } : {}) }; }
export function saveRetentionReleaseReverseAttempt(storage: Storage, attempt: RetentionReleaseReverseAttempt) { storage.setItem(retentionReleaseReverseStorageKey(attempt.userId, attempt.companyId, attempt.releaseId), JSON.stringify(attempt)); }
const inFlight = new Map<string, Promise<RetentionReleaseReverseAttempt>>();
export function sendRetentionReleaseReverseAttempt(client: SupabaseClient<Database>, storage: Storage, attempt: RetentionReleaseReverseAttempt, firstSend = false): Promise<RetentionReleaseReverseAttempt> { if (attempt.receipt) return Promise.resolve(attempt); const lock = retentionReleaseReverseStorageKey(attempt.userId, attempt.companyId, attempt.releaseId); const running = inFlight.get(lock); if (running) return running; const run = (async () => { saveRetentionReleaseReverseAttempt(storage, attempt); const { data, error } = await client.auth.getSession(); if (error || data.session?.user.id !== attempt.userId) throw new Error("denied"); let receipt: RetentionReleaseReverseReceipt; try { receipt = await reverseRetentionRelease(client, attempt.companyId, attempt.releaseId, attempt.key, attempt.input); } catch (error) { if (firstSend && error instanceof RetentionReleaseReverseError && error.rejected) { storage.removeItem(lock); throw new Error("rejected"); } throw error; } const completed = { ...attempt, receipt }; try { saveRetentionReleaseReverseAttempt(storage, completed); } catch { /* frozen request remains replayable */ } return completed; })(); inFlight.set(lock, run); void run.finally(() => { if (inFlight.get(lock) === run) inFlight.delete(lock); }).catch(() => {}); return run; }
