import type { SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "../types/database.generated";
import { RetentionPaymentReverseError, normalizeRetentionPaymentReverseInput, reverseRetentionPayment, retentionPaymentReversePayload, validRetentionPaymentReverseReceipt, type RetentionPaymentReverseInput, type RetentionPaymentReverseReceipt } from "./retentionPaymentReverseRepository";
export interface RetentionPaymentReverseAttempt { version: 1; userId: string; companyId: string; paymentId: string; key: string; input: RetentionPaymentReverseInput; receipt?: RetentionPaymentReverseReceipt; }
export const retentionPaymentReverseStorageKey = (userId: string, companyId: string, paymentId: string) => `makeracc:retention-payment-reverse:${userId}:${companyId}:${paymentId}`;
export function loadRetentionPaymentReverseAttempt(storage: Storage, userId: string, companyId: string, paymentId: string): RetentionPaymentReverseAttempt | null { const text = storage.getItem(retentionPaymentReverseStorageKey(userId, companyId, paymentId)); if (!text) return null; const value = JSON.parse(text) as RetentionPaymentReverseAttempt; if (value.version !== 1 || value.userId !== userId || value.companyId !== companyId || value.paymentId !== paymentId || (value.receipt !== undefined && !validRetentionPaymentReverseReceipt(value.receipt))) throw new Error("recovery"); const input = normalizeRetentionPaymentReverseInput(value.input); retentionPaymentReversePayload(companyId, paymentId, value.key, input); return { version: 1, userId, companyId, paymentId, key: value.key, input, ...(value.receipt ? { receipt: value.receipt } : {}) }; }
export function saveRetentionPaymentReverseAttempt(storage: Storage, attempt: RetentionPaymentReverseAttempt) { storage.setItem(retentionPaymentReverseStorageKey(attempt.userId, attempt.companyId, attempt.paymentId), JSON.stringify(attempt)); }
const inFlight = new Map<string, Promise<RetentionPaymentReverseAttempt>>();
export function sendRetentionPaymentReverseAttempt(client: SupabaseClient<Database>, storage: Storage, attempt: RetentionPaymentReverseAttempt, firstSend = false): Promise<RetentionPaymentReverseAttempt> { if (attempt.receipt) return Promise.resolve(attempt); const lock = retentionPaymentReverseStorageKey(attempt.userId, attempt.companyId, attempt.paymentId); const running = inFlight.get(lock); if (running) return running; const run = (async () => { saveRetentionPaymentReverseAttempt(storage, attempt); const { data, error } = await client.auth.getSession(); if (error || data.session?.user.id !== attempt.userId) throw new Error("denied"); let receipt: RetentionPaymentReverseReceipt; try { receipt = await reverseRetentionPayment(client, attempt.companyId, attempt.paymentId, attempt.key, attempt.input); } catch (error) { if (firstSend && error instanceof RetentionPaymentReverseError && error.rejected) { storage.removeItem(lock); throw new Error("rejected"); } throw error; } const completed = { ...attempt, receipt }; try { saveRetentionPaymentReverseAttempt(storage, completed); } catch { /* frozen request remains replayable */ } return completed; })(); inFlight.set(lock, run); void run.finally(() => { if (inFlight.get(lock) === run) inFlight.delete(lock); }).catch(() => {}); return run; }
