import type { SupabaseClient } from "@supabase/supabase-js"; import type { Database } from "../types/database.generated";
export type DeductionType="COMPANY_MATERIALS"|"BACKCHARGE"|"OTHER"; export interface CertificateDeductionInput{type:DeductionType;description:string;amount_minor:string} export interface CertificateDraftInput{date:string;subcontractId:string;contractorNumber:string;workToDateMinor:string;variationMinor:string;advanceRecoveryMinor:string;vatMode:"ZERO"|"AUTO_5"|"MANUAL";manualVatMinor:string|null;taxInvoiceReceived:boolean;taxInvoiceNumber:string|null;taxInvoiceDate:string|null;deductions:CertificateDeductionInput[];notes:string|null} export interface CertificateDraftReceipt{subcontractor_certificate_id:string;certificate_reference:string}
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;const exact=(value:unknown)=>typeof value==="string"&&/^\d+$/.test(value)&&BigInt(value)<=9000000000000000n;const date=(value:string)=>/^\d{4}-\d{2}-\d{2}$/.test(value)&&Number.isFinite(Date.parse(value))&&new Date(value).toISOString().slice(0,10)===value;
export const canCreateCertificateDraft=(role:string)=>role==="ACCOUNTING_ADMIN"||role==="ACCOUNTANT";
export function parseCertificateAED(value:string,positive=false){if(!/^\d+(\.\d{1,2})?$/.test(value.trim()))throw new Error("invalid");const[w,f=""]=value.trim().split(".");const result=BigInt(w)*100n+BigInt(f.padEnd(2,"0"));if(result>(9000000000000000n)||(positive&&result<1n))throw new Error("invalid");return result.toString();}
export function normalizeCertificateDraftInput(input:CertificateDraftInput):CertificateDraftInput{if(!input||!date(input.date)||!uuid.test(input.subcontractId)||typeof input.contractorNumber!=="string"||![...input.contractorNumber.trim()].length||[...input.contractorNumber.trim()].length>100||![input.workToDateMinor,input.variationMinor,input.advanceRecoveryMinor].every(exact)||!["ZERO","AUTO_5","MANUAL"].includes(input.vatMode)||input.deductions.length>100)throw new Error("invalid");const manual=input.manualVatMinor===null?null:BigInt(input.manualVatMinor).toString();if(input.vatMode==="MANUAL"?!exact(manual):manual!==null&&manual!=="0")throw new Error("invalid");const invoice=input.taxInvoiceNumber?.trim()||null,notes=input.notes?.trim()||null;if((invoice&&[...invoice].length>200)||(notes&&[...notes].length>2000)||(input.taxInvoiceDate!==null&&!date(input.taxInvoiceDate))||(!input.taxInvoiceReceived&&(invoice!==null||input.taxInvoiceDate!==null)))throw new Error("invalid");const deductions=input.deductions.map(row=>{const description=row.description.trim();if(!["COMPANY_MATERIALS","BACKCHARGE","OTHER"].includes(row.type)||!description||[...description].length>500||!exact(row.amount_minor)||BigInt(row.amount_minor)<1n)throw new Error("invalid");return{type:row.type,description,amount_minor:BigInt(row.amount_minor).toString()};});return{...input,contractorNumber:input.contractorNumber.trim(),workToDateMinor:BigInt(input.workToDateMinor).toString(),variationMinor:BigInt(input.variationMinor).toString(),advanceRecoveryMinor:BigInt(input.advanceRecoveryMinor).toString(),manualVatMinor:manual,taxInvoiceNumber:invoice,taxInvoiceDate:input.taxInvoiceDate,taxInvoiceReceived:input.taxInvoiceReceived,deductions,notes};}
export function certificateDraftPayload(companyId:string,raw:CertificateDraftInput){if(!uuid.test(companyId))throw new Error("invalid");const i=normalizeCertificateDraftInput(raw);return{target_company_id:companyId,target_certificate_date:i.date,target_subcontract_id:i.subcontractId,target_contractor_certificate_number:i.contractorNumber,target_work_value_to_date_minor:i.workToDateMinor,target_current_variation_amount_minor:i.variationMinor,target_advance_recovery_minor:i.advanceRecoveryMinor,target_vat_mode:i.vatMode,target_manual_vat_amount_minor:i.manualVatMinor,target_tax_invoice_received:i.taxInvoiceReceived,target_tax_invoice_number:i.taxInvoiceNumber,target_tax_invoice_date:i.taxInvoiceDate,target_deductions:i.deductions,target_notes:i.notes};}
export class CertificateDraftError extends Error{readonly rejected:boolean;constructor(rejected:boolean){super("unresolved");this.rejected=rejected}}
export function validCertificateDraftReceipt(v:unknown):v is CertificateDraftReceipt{if(!v||typeof v!=="object")return false;const r=v as CertificateDraftReceipt;return uuid.test(r.subcontractor_certificate_id)&&typeof r.certificate_reference==="string"&&!!r.certificate_reference;}
type DraftDb=Omit<Database,"public">&{public:Omit<Database["public"],"Functions">&{Functions:Omit<Database["public"]["Functions"],"create_subcontractor_certificate_draft">&{create_subcontractor_certificate_draft:{Args:ReturnType<typeof certificateDraftPayload>;Returns:CertificateDraftReceipt[]}}}};
export async function createCertificateDraft(client:SupabaseClient<Database>,companyId:string,input:CertificateDraftInput){const{data,error}=await(client as unknown as SupabaseClient<DraftDb>).rpc("create_subcontractor_certificate_draft",certificateDraftPayload(companyId,input));if(error)throw new CertificateDraftError(["22003","22023","23503","23505","23514","42501","23502","22P02","22007"].includes(error.code));if(!data||data.length!==1||!validCertificateDraftReceipt(data[0]))throw new CertificateDraftError(false);return data[0];}
