import type { SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "../types/database.generated";
export interface SubcontractorAdvanceInput { date: string; subcontractId: string; treasuryId: string; amountMinor: string; method: Database["public"]["Enums"]["payment_method"]; externalReference: string | null; notes: string | null; }
export interface SubcontractorAdvanceReceipt { subcontractor_advance_id: string; advance_reference: string; journal_entry_id: string; replayed: boolean; }
const uuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const money = (value: unknown) => typeof value === "string" && /^\d+$/.test(value) && BigInt(value) >= 1n && BigInt(value) <= 9000000000000000n;
export const canPostSubcontractorAdvance = (role: string) => role === "ACCOUNTING_ADMIN" || role === "ACCOUNTANT";
export function parseSubcontractorAdvanceAED(value: string) { if (!/^\d+(\.\d{1,2})?$/.test(value.trim())) throw new Error("invalid"); const [whole, fraction = ""] = value.trim().split("."); const result = BigInt(whole) * 100n + BigInt(fraction.padEnd(2, "0")); if (result < 1n || result > 9000000000000000n) throw new Error("invalid"); return result.toString(); }
export function normalizeSubcontractorAdvanceInput(input: SubcontractorAdvanceInput): SubcontractorAdvanceInput {
  if (!input || !/^\d{4}-\d{2}-\d{2}$/.test(input.date) || !Number.isFinite(Date.parse(input.date)) || new Date(input.date).toISOString().slice(0, 10) !== input.date
    || !uuid.test(input.subcontractId) || !uuid.test(input.treasuryId) || !money(input.amountMinor) || !["CASH", "BANK", "TRANSFER", "CHEQUE", "OTHER"].includes(input.method)) throw new Error("invalid");
  const externalReference = input.externalReference?.trim() || null; const notes = input.notes?.trim() || null;
  if ((externalReference && [...externalReference].length > 200) || (notes && [...notes].length > 2000)) throw new Error("invalid");
  return { date: input.date, subcontractId: input.subcontractId, treasuryId: input.treasuryId, amountMinor: BigInt(input.amountMinor).toString(), method: input.method, externalReference, notes };
}
export function subcontractorAdvancePayload(companyId: string, key: string, raw: SubcontractorAdvanceInput) { if (!uuid.test(companyId) || !uuid.test(key)) throw new Error("invalid"); const input = normalizeSubcontractorAdvanceInput(raw); return { target_company_id: companyId, target_advance_date: input.date, target_subcontract_id: input.subcontractId, target_treasury_account_id: input.treasuryId, target_amount_minor: input.amountMinor, target_payment_method: input.method, target_external_reference: input.externalReference, target_notes: input.notes, target_idempotency_key: key }; }
type PostDatabase = Omit<Database, "public"> & { public: Omit<Database["public"], "Functions"> & { Functions: Omit<Database["public"]["Functions"], "post_subcontractor_advance"> & { post_subcontractor_advance: { Args: ReturnType<typeof subcontractorAdvancePayload>; Returns: SubcontractorAdvanceReceipt[] } } } };
export function validSubcontractorAdvanceReceipt(value: unknown): value is SubcontractorAdvanceReceipt { if (!value || typeof value !== "object") return false; const row = value as SubcontractorAdvanceReceipt; return uuid.test(row.subcontractor_advance_id) && uuid.test(row.journal_entry_id) && typeof row.advance_reference === "string" && !!row.advance_reference && typeof row.replayed === "boolean"; }
export class SubcontractorAdvancePostError extends Error { readonly rejected: boolean; constructor(rejected: boolean) { super("unresolved"); this.rejected = rejected; } }
export async function postSubcontractorAdvance(client: SupabaseClient<Database>, companyId: string, key: string, input: SubcontractorAdvanceInput) { const { data, error } = await (client as unknown as SupabaseClient<PostDatabase>).rpc("post_subcontractor_advance", subcontractorAdvancePayload(companyId, key, input)); if (error) throw new SubcontractorAdvancePostError(["22003", "22023", "23503", "23514", "42501", "23502", "22P02", "22007"].includes(error.code)); if (!data || data.length !== 1 || !validSubcontractorAdvanceReceipt(data[0])) throw new SubcontractorAdvancePostError(false); return data[0]; }
