import { useEffect, useRef, useState, type FormEvent } from "react";
import { useT } from "../i18n/I18nContext"; import { getSupabaseClient } from "../lib/supabase"; import { useProductionMasterData } from "../master/productionMasterDataContext";
import { displayMinor } from "./expenseRepository"; import { readSubcontractorAdvanceById, type SubcontractorAdvanceRead } from "./subcontractorAdvanceRepository";
import { loadSubcontractorAdvanceAttempt, saveSubcontractorAdvanceAttempt, sendSubcontractorAdvanceAttempt, subcontractorAdvanceAttemptStorageKey, type SubcontractorAdvanceAttempt } from "./subcontractorAdvancePostAttempt";
import { canPostSubcontractorAdvance, normalizeSubcontractorAdvanceInput, parseSubcontractorAdvanceAED, type SubcontractorAdvanceInput } from "./subcontractorAdvancePostRepository";

export function SubcontractorAdvancePost({ userId, companyId, role, onPosted }: { userId: string; companyId: string; role: string; onPosted: () => void }) {
  const t = useT(); const master = useProductionMasterData(); const [initial] = useState(() => { try { return { attempt: loadSubcontractorAdvanceAttempt(window.sessionStorage, userId, companyId), ready: true }; } catch { return { attempt: null, ready: false }; } });
  const [attempt, setAttempt] = useState<SubcontractorAdvanceAttempt | null>(initial.attempt); const [ready, setReady] = useState(initial.ready); const [busy, setBusy] = useState(false); const [posted, setPosted] = useState<SubcontractorAdvanceRead | null>(null);
  const [message, setMessage] = useState<"invalid" | "unresolved" | "rejected" | "readError" | "storageError" | "denied" | null>(initial.ready ? null : "storageError"); const [subcontractId, setSubcontractId] = useState(""); const [formKey, setFormKey] = useState(0); const generation = useRef(0); const lock = useRef(false);
  useEffect(() => { const { data } = getSupabaseClient().auth.onAuthStateChange((event, session) => { if (event === "SIGNED_OUT" || !session || session.user.id !== userId) { generation.current++; setReady(false); setAttempt(null); setPosted(null); setMessage("denied"); } }); const invalidate = () => { generation.current++; }; return () => { invalidate(); data.subscription.unsubscribe(); }; }, [userId, companyId]);
  const recover = async (pending: SubcontractorAdvanceAttempt, firstSend = false) => { if (lock.current || !ready || !canPostSubcontractorAdvance(role)) return; lock.current = true; setBusy(true); setMessage(null); const version = generation.current; const current = () => generation.current === version; let confirmed = pending;
    try { confirmed = await sendSubcontractorAdvanceAttempt(getSupabaseClient(), window.sessionStorage, pending, firstSend); if (!current()) return; setAttempt(confirmed); const row = await readSubcontractorAdvanceById(getSupabaseClient(), companyId, confirmed.receipt!.subcontractor_advance_id); const live = await getSupabaseClient().auth.getSession(); if (!current()) return; if (live.error || live.data.session?.user.id !== userId) { setReady(false); setAttempt(null); setMessage("denied"); return; } if (row.status !== "POSTED" || row.posted_journal_entry_id !== confirmed.receipt!.journal_entry_id || row.subcontract_id !== pending.input.subcontractId || row.treasury_account_id !== pending.input.treasuryId || row.amount_minor !== pending.input.amountMinor) throw new Error("readback"); setPosted(row); onPosted();
    } catch (error) { if (current()) { if (firstSend && error instanceof Error && error.message === "rejected") { setAttempt(null); setMessage("rejected"); } else { setAttempt(confirmed); setMessage(confirmed.receipt ? "readError" : "unresolved"); } } } finally { if (current()) { lock.current = false; setBusy(false); } } };
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (attempt || busy || !ready || master.phase !== "READY" || !canPostSubcontractorAdvance(role)) return; const data = new FormData(event.currentTarget); const value = (name: string) => String(data.get(name) ?? "");
    try { const contract = master.subcontracts.find(row => row.companyId === companyId && row.id === subcontractId && row.status === "ACTIVE"); if (!contract) throw new Error("invalid"); const project = master.projects.find(row => row.companyId === companyId && row.id === contract.projectId && row.status !== "CLOSED"); const party = master.parties.find(row => row.companyId === companyId && row.id === contract.subcontractorId && row.type === "SUBCONTRACTOR" && row.status === "ACTIVE"); const treasury = master.treasuryAccounts.find(row => row.companyId === companyId && row.id === value("treasury") && row.status === "ACTIVE" && (row.projectId === null || row.projectId === contract.projectId)); const gl = treasury && master.accounts.find(row => row.companyId === companyId && row.id === treasury.glAccountId && row.status === "ACTIVE" && row.accountType === "ASSET"); if (!project || !party || !treasury || !gl) throw new Error("invalid");
      const input = normalizeSubcontractorAdvanceInput({ date: value("date"), subcontractId, treasuryId: treasury.id, amountMinor: parseSubcontractorAdvanceAED(value("amount")), method: value("method") as SubcontractorAdvanceInput["method"], externalReference: value("externalReference") || null, notes: value("notes") || null }); const pending: SubcontractorAdvanceAttempt = { version: 1, userId, companyId, key: crypto.randomUUID(), input }; saveSubcontractorAdvanceAttempt(window.sessionStorage, pending); setAttempt(pending); void recover(pending, true);
    } catch (error) { setMessage(error instanceof Error && error.message === "invalid" ? "invalid" : "storageError"); } };
  if (!canPostSubcontractorAdvance(role)) return null; const field = "block w-full rounded-lg border border-slate-300 bg-white px-3 py-2"; const contract = master.phase === "READY" ? master.subcontracts.find(row => row.id === subcontractId && row.companyId === companyId) : null; const partyName = contract && master.phase === "READY" ? master.parties.find(row => row.id === contract.subcontractorId)?.name : null; const projectName = contract && master.phase === "READY" ? master.projects.find(row => row.id === contract.projectId)?.name : null;
  return <section className="mt-5 rounded-xl border p-4" aria-label={t("subcontractorAdvancePost.title")}><h3 className="font-semibold">{t("subcontractorAdvancePost.title")}</h3><p className="mt-2 text-sm text-slate-600">{t("subcontractorAdvancePost.scope")}</p>{message && <p role="alert" className="mt-3 text-red-800">{t(`subcontractorAdvancePost.${message}`)}</p>}{busy && <p role="status">{t("subcontractorAdvancePost.pending")}</p>}
    {attempt ? <div className="mt-3 space-y-2 break-words"><p>{t(attempt.receipt ? "subcontractorAdvancePost.confirmed" : "subcontractorAdvancePost.frozen")}</p><p><bdi>{displayMinor(attempt.input.amountMinor)} AED · {attempt.key}</bdi></p>{attempt.receipt && <p><bdi>{attempt.receipt.advance_reference} · {attempt.receipt.journal_entry_id}</bdi></p>}{posted && <p role="status"><bdi>{posted.advance_reference} · {t(`subcontractorAdvanceRead.${posted.status}`)} · {displayMinor(posted.amount_minor)} AED</bdi></p>}<button type="button" className={field} disabled={busy || !ready} onClick={() => void recover(attempt)}>{t(attempt.receipt ? "subcontractorAdvancePost.readAgain" : "subcontractorAdvancePost.retry")}</button>{attempt.receipt && <button type="button" className={field} disabled={busy || !posted} onClick={() => { try { window.sessionStorage.removeItem(subcontractorAdvanceAttemptStorageKey(userId, companyId)); setAttempt(null); setPosted(null); setMessage(null); setSubcontractId(""); setFormKey(value => value + 1); } catch { setMessage("storageError"); } }}>{t("subcontractorAdvancePost.new")}</button>}</div>
    : master.phase !== "READY" ? <p role="status">{t("subcontractorAdvancePost.masters")}</p> : <form key={formKey} onSubmit={submit} className="mt-4"><fieldset disabled={busy || !ready} className="grid gap-3 sm:grid-cols-2"><label>{t("subcontractorAdvancePost.date")}<input name="date" type="date" required className={field} /></label><label>{t("subcontractorAdvancePost.subcontract")}<select required value={subcontractId} onChange={event => setSubcontractId(event.target.value)} className={field}><option value="">{t("expensePost.select")}</option>{master.subcontracts.filter(row => row.companyId === companyId && row.status === "ACTIVE" && master.projects.some(project => project.id === row.projectId && project.status !== "CLOSED") && master.parties.some(party => party.id === row.subcontractorId && party.type === "SUBCONTRACTOR" && party.status === "ACTIVE")).map(row => <option key={row.id} value={row.id}>{row.contractNumber} · {row.scopeOfWork}</option>)}</select></label>{contract && <p className="sm:col-span-2"><bdi>{projectName ?? contract.projectId} · {partyName ?? contract.subcontractorId}</bdi></p>}<label>{t("subcontractorAdvancePost.treasury")}<select name="treasury" key={subcontractId} required defaultValue="" className={field}><option value="">{t("expensePost.select")}</option>{contract && master.treasuryAccounts.filter(row => row.companyId === companyId && row.status === "ACTIVE" && (row.projectId === null || row.projectId === contract.projectId) && master.accounts.some(account => account.id === row.glAccountId && account.status === "ACTIVE" && account.accountType === "ASSET")).map(row => <option key={row.id} value={row.id}>{row.code} · {row.name}</option>)}</select></label><label>{t("subcontractorAdvancePost.amount")}<input name="amount" required inputMode="decimal" placeholder="0.00" className={field} /></label><label>{t("expenseRead.method")}<select name="method" required defaultValue="" className={field}><option value="">{t("expensePost.select")}</option>{(["CASH", "BANK", "TRANSFER", "CHEQUE", "OTHER"] as const).map(value => <option key={value} value={value}>{t(`expenseRead.${value}`)}</option>)}</select></label><label>{t("subcontractorAdvancePost.externalReference")}<input name="externalReference" maxLength={200} className={field} /></label><label className="sm:col-span-2">{t("expenseRead.notes")}<textarea name="notes" maxLength={2000} className={field} /></label><button type="submit" className="rounded-lg bg-[var(--tenant-primary)] px-4 py-2 text-white sm:col-span-2">{t("subcontractorAdvancePost.submit")}</button></fieldset></form>}
  </section>;
}
