import { useState } from "react";
import { useAuth } from "../auth/AuthContext";
import { useT } from "../i18n/I18nContext";
import { getSupabaseClient } from "../lib/supabase";
import { useProductionMasterData } from "../master/productionMasterDataContext";
import { displayMinor } from "./expenseRepository";
import { SubcontractorPaymentPost } from "./SubcontractorPaymentPost";
import { SubcontractorPaymentReverseAction } from "./SubcontractorPaymentReverseAction";
import { canReadSubcontractorPayments } from "./subcontractorPaymentRepository";
import { useSubcontractorPaymentRead } from "./useSubcontractorPaymentRead";

export function SubcontractorPaymentPanel() { const { state } = useAuth(); if (state.phase !== "TENANT_READY") return null; return <SubcontractorPaymentContent key={`${state.profile.userId}:${state.activeTenant.companyId}:${state.activeTenant.role}`} userId={state.profile.userId} companyId={state.activeTenant.companyId} role={state.activeTenant.role} />; }
export function SubcontractorPaymentContent({ userId, companyId, role }: { userId: string; companyId: string; role: string }) {
  const t = useT(); const master = useProductionMasterData(); const [revision, setRevision] = useState(0); const state = useSubcontractorPaymentRead(getSupabaseClient(), userId, companyId, role, revision); const refresh = () => setRevision(value => value + 1);
  if (!canReadSubcontractorPayments(role)) return <section className="rounded-2xl border bg-white p-6"><h2 className="text-2xl font-semibold">{t("subcontractorPaymentRead.title")}</h2><p role="alert" className="mt-4">{t("subcontractorPaymentRead.denied")}</p></section>;
  const partyName = (id: string) => master.phase === "READY" ? master.parties.find(row => row.id === id)?.name ?? id : id; const treasuryName = (id: string) => master.phase === "READY" ? master.treasuryAccounts.find(row => row.id === id)?.name ?? id : id; const projectName = (id: string) => master.phase === "READY" ? master.projects.find(row => row.id === id)?.name ?? id : id; const subcontractName = (id: string) => master.phase === "READY" ? master.subcontracts.find(row => row.id === id)?.contractNumber ?? id : id;
  return <section className="min-w-0 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-2xl font-semibold">{t("subcontractorPaymentRead.title")}</h2><p className="mt-3 text-sm text-slate-500">{t("subcontractorPaymentRead.scope")}</p>
    <SubcontractorPaymentPost userId={userId} companyId={companyId} role={role} outstanding={state.phase === "READY" ? state.outstanding : []} onPosted={refresh} />
    <button type="button" onClick={refresh} disabled={state.phase === "LOADING"} className="mt-4 rounded-lg border px-3 py-2 disabled:opacity-50">{t("subcontractorPaymentRead.refresh")}</button>
    {state.phase === "LOADING" && <p role="status" className="mt-4">{t("subcontractorPaymentRead.loading")}</p>}{state.phase === "ERROR" && <p role="alert" className="mt-4 text-red-800">{t("subcontractorPaymentRead.error")}</p>}
    {state.phase === "READY" && <><section className="mt-5"><h3 className="font-semibold">{t("subcontractorPaymentRead.outstanding")}</h3>{state.outstanding.length === 0 ? <p role="status" className="mt-2">{t("subcontractorPaymentRead.noOutstanding")}</p> : <ul className="mt-2 divide-y">{state.outstanding.map(row => <li key={row.id} className="py-3"><p><bdi>{row.certificate_reference} · {subcontractName(row.subcontract_id)} · {partyName(row.subcontractor_id)} · {displayMinor(row.outstanding_amount_minor)} AED</bdi></p><p className="text-sm text-slate-600"><bdi>{row.certificate_date} · {projectName(row.project_id)}</bdi></p></li>)}</ul>}</section>
      <section className="mt-6"><h3 className="font-semibold">{t("subcontractorPaymentRead.history")}</h3>{state.payments.length === 0 ? <p role="status" className="mt-2">{t("subcontractorPaymentRead.empty")}</p> : <ul className="mt-2 divide-y">{state.payments.map(row => { const allocations = state.allocations.filter(item => item.subcontractor_payment_id === row.id); return <li key={row.id} className="min-w-0 break-words py-4"><div className="flex flex-wrap justify-between gap-3"><h4 className="font-semibold"><bdi>{row.payment_reference}</bdi></h4><span>{t(`subcontractorPaymentRead.${row.status}`)}</span></div><p><bdi>{row.payment_date} · {subcontractName(row.subcontract_id)} · {projectName(row.project_id)} · {partyName(row.subcontractor_id)} · {treasuryName(row.treasury_account_id)} · {displayMinor(row.total_amount_minor)} AED</bdi></p><p className="text-sm"><bdi>{t(`expenseRead.${row.payment_method}`)}{row.external_reference ? ` · ${row.external_reference}` : ""}</bdi></p>{row.notes && <p className="whitespace-pre-wrap text-sm"><bdi>{row.notes}</bdi></p>}<details className="mt-2"><summary>{t("subcontractorPaymentRead.allocations")}</summary><ul>{allocations.map(item => <li key={item.id}><bdi>{item.subcontractor_certificate_id} · {displayMinor(item.allocated_amount_minor)} AED</bdi></li>)}</ul><p><bdi>{t("subcontractorPaymentRead.postedJournal")}: {row.posted_journal_entry_id ?? t("expenseRead.absent")}</bdi></p>{row.reversal_journal_entry_id && <p><bdi>{t("subcontractorPaymentRead.reversalJournal")}: {row.reversal_journal_entry_id}</bdi></p>}<p><bdi>{t("subcontractorPaymentRead.created")}: {row.created_at} · {row.created_by ?? t("expenseRead.absent")}</bdi></p>{row.posted_at && <p><bdi>{t("subcontractorPaymentRead.posted")}: {row.posted_at} · {row.posted_by ?? t("expenseRead.absent")}</bdi></p>}{row.reversed_at && <p><bdi>{t("subcontractorPaymentRead.reversed")}: {row.reversed_at} · {row.reversed_by ?? t("expenseRead.absent")} · {row.reversal_reason}</bdi></p>}</details><SubcontractorPaymentReverseAction userId={userId} companyId={companyId} role={role} payment={row} onRefresh={refresh} /></li>; })}</ul>}</section></>}
  </section>;
}
