import type { SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "../types/database.generated";
import { SubcontractorPaymentReverseError, normalizeSubcontractorPaymentReverseInput, reverseSubcontractorPayment, subcontractorPaymentReversePayload, validSubcontractorPaymentReverseReceipt, type SubcontractorPaymentReverseInput, type SubcontractorPaymentReverseReceipt } from "./subcontractorPaymentReverseRepository";
export interface SubcontractorPaymentReverseAttempt { version: 1; userId: string; companyId: string; paymentId: string; key: string; input: SubcontractorPaymentReverseInput; receipt?: SubcontractorPaymentReverseReceipt; }
export const subcontractorPaymentReverseStorageKey = (userId: string, companyId: string, paymentId: string) => `makeracc:subcontractor-payment-reverse:${userId}:${companyId}:${paymentId}`;
export function loadSubcontractorPaymentReverseAttempt(storage: Storage, userId: string, companyId: string, paymentId: string): SubcontractorPaymentReverseAttempt | null { const text = storage.getItem(subcontractorPaymentReverseStorageKey(userId, companyId, paymentId)); if (!text) return null; const value = JSON.parse(text) as SubcontractorPaymentReverseAttempt; if (value.version !== 1 || value.userId !== userId || value.companyId !== companyId || value.paymentId !== paymentId || (value.receipt !== undefined && !validSubcontractorPaymentReverseReceipt(value.receipt))) throw new Error("recovery"); const input = normalizeSubcontractorPaymentReverseInput(value.input); subcontractorPaymentReversePayload(companyId, paymentId, value.key, input); return { version: 1, userId, companyId, paymentId, key: value.key, input, ...(value.receipt ? { receipt: value.receipt } : {}) }; }
export function saveSubcontractorPaymentReverseAttempt(storage: Storage, attempt: SubcontractorPaymentReverseAttempt) { storage.setItem(subcontractorPaymentReverseStorageKey(attempt.userId, attempt.companyId, attempt.paymentId), JSON.stringify(attempt)); }
const inFlight = new Map<string, Promise<SubcontractorPaymentReverseAttempt>>();
export function sendSubcontractorPaymentReverseAttempt(client: SupabaseClient<Database>, storage: Storage, attempt: SubcontractorPaymentReverseAttempt, firstSend = false): Promise<SubcontractorPaymentReverseAttempt> { if (attempt.receipt) return Promise.resolve(attempt); const lock = subcontractorPaymentReverseStorageKey(attempt.userId, attempt.companyId, attempt.paymentId); const running = inFlight.get(lock); if (running) return running; const run = (async () => { saveSubcontractorPaymentReverseAttempt(storage, attempt); const { data, error } = await client.auth.getSession(); if (error || data.session?.user.id !== attempt.userId) throw new Error("denied"); let receipt: SubcontractorPaymentReverseReceipt; try { receipt = await reverseSubcontractorPayment(client, attempt.companyId, attempt.paymentId, attempt.key, attempt.input); } catch (error) { if (firstSend && error instanceof SubcontractorPaymentReverseError && error.rejected) { storage.removeItem(lock); throw new Error("rejected"); } throw error; } const completed = { ...attempt, receipt }; try { saveSubcontractorPaymentReverseAttempt(storage, completed); } catch { /* frozen request remains replayable */ } return completed; })(); inFlight.set(lock, run); void run.finally(() => { if (inFlight.get(lock) === run) inFlight.delete(lock); }).catch(() => {}); return run; }
