import type { SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "../types/database.generated";
export interface SubcontractorPaymentReverseInput { date: string; reason: string; }
export interface SubcontractorPaymentReverseReceipt { subcontractor_payment_id: string; payment_reference: string; reversal_journal_entry_id: string; replayed: boolean; }
const uuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
export const canReverseSubcontractorPayment = (role: string, status: string) => role === "ACCOUNTING_ADMIN" && status === "POSTED";
export function normalizeSubcontractorPaymentReverseInput(input: SubcontractorPaymentReverseInput) { if (!input || !/^\d{4}-\d{2}-\d{2}$/.test(input.date) || !Number.isFinite(Date.parse(input.date)) || new Date(input.date).toISOString().slice(0, 10) !== input.date || typeof input.reason !== "string") throw new Error("invalid"); const reason = input.reason.trim(); if (!reason || [...reason].length > 1000) throw new Error("invalid"); return { date: input.date, reason }; }
export function subcontractorPaymentReversePayload(companyId: string, paymentId: string, key: string, raw: SubcontractorPaymentReverseInput) { if (!uuid.test(companyId) || !uuid.test(paymentId) || !uuid.test(key)) throw new Error("invalid"); const input = normalizeSubcontractorPaymentReverseInput(raw); return { target_company_id: companyId, target_subcontractor_payment_id: paymentId, target_reversal_date: input.date, target_reason: input.reason, target_idempotency_key: key }; }
export function validSubcontractorPaymentReverseReceipt(value: unknown): value is SubcontractorPaymentReverseReceipt { if (!value || typeof value !== "object") return false; const row = value as SubcontractorPaymentReverseReceipt; return uuid.test(row.subcontractor_payment_id) && uuid.test(row.reversal_journal_entry_id) && typeof row.payment_reference === "string" && !!row.payment_reference && typeof row.replayed === "boolean"; }
export class SubcontractorPaymentReverseError extends Error { readonly rejected: boolean; constructor(rejected: boolean) { super("unresolved"); this.rejected = rejected; } }
export async function reverseSubcontractorPayment(client: SupabaseClient<Database>, companyId: string, paymentId: string, key: string, input: SubcontractorPaymentReverseInput): Promise<SubcontractorPaymentReverseReceipt> { const { data, error } = await client.rpc("reverse_subcontractor_payment", subcontractorPaymentReversePayload(companyId, paymentId, key, input)); if (error) throw new SubcontractorPaymentReverseError(true); if (!data || data.length !== 1 || !validSubcontractorPaymentReverseReceipt(data[0])) throw new SubcontractorPaymentReverseError(false); return data[0]; }
