import type { SupabaseClient } from "@supabase/supabase-js"; import type { Database } from "../types/database.generated";
export interface SubcontractorAdvanceReverseInput { date: string; reason: string; }
export interface SubcontractorAdvanceReverseReceipt { subcontractor_advance_id: string; advance_reference: string; reversal_journal_entry_id: string; replayed: boolean; }
const uuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
export const canReverseSubcontractorAdvance = (role: string, status: string) => role === "ACCOUNTING_ADMIN" && status === "POSTED";
export function normalizeSubcontractorAdvanceReverseInput(input: SubcontractorAdvanceReverseInput) { if (!input || !/^\d{4}-\d{2}-\d{2}$/.test(input.date) || !Number.isFinite(Date.parse(input.date)) || new Date(input.date).toISOString().slice(0, 10) !== input.date || typeof input.reason !== "string") throw new Error("invalid"); const reason = input.reason.trim(); if (!reason || [...reason].length > 1000) throw new Error("invalid"); return { date: input.date, reason }; }
export function subcontractorAdvanceReversePayload(companyId: string, advanceId: string, key: string, raw: SubcontractorAdvanceReverseInput) { if (!uuid.test(companyId) || !uuid.test(advanceId) || !uuid.test(key)) throw new Error("invalid"); const input = normalizeSubcontractorAdvanceReverseInput(raw); return { target_company_id: companyId, target_subcontractor_advance_id: advanceId, target_reversal_date: input.date, target_reason: input.reason, target_idempotency_key: key }; }
export function validSubcontractorAdvanceReverseReceipt(value: unknown): value is SubcontractorAdvanceReverseReceipt { if (!value || typeof value !== "object") return false; const row = value as SubcontractorAdvanceReverseReceipt; return uuid.test(row.subcontractor_advance_id) && uuid.test(row.reversal_journal_entry_id) && typeof row.advance_reference === "string" && !!row.advance_reference && typeof row.replayed === "boolean"; }
export class SubcontractorAdvanceReverseError extends Error { readonly rejected: boolean; constructor(rejected: boolean) { super("unresolved"); this.rejected = rejected; } }
export async function reverseSubcontractorAdvance(client: SupabaseClient<Database>, companyId: string, advanceId: string, key: string, input: SubcontractorAdvanceReverseInput) { const { data, error } = await client.rpc("reverse_subcontractor_advance", subcontractorAdvanceReversePayload(companyId, advanceId, key, input)); if (error) throw new SubcontractorAdvanceReverseError(["22003", "22023", "23503", "23514", "42501", "23502", "22P02", "22007"].includes(error.code)); if (!data || data.length !== 1 || !validSubcontractorAdvanceReverseReceipt(data[0])) throw new SubcontractorAdvanceReverseError(false); return data[0]; }
