import type { SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "../types/database.generated";

export type CertificateStatus = "DRAFT" | "POSTED" | "REVERSED";
export interface SubcontractorCertificateRead {
  id: string; company_id: string; certificate_reference: string; contractor_certificate_number: string; certificate_date: string;
  project_id: string; subcontractor_id: string; subcontract_id: string; work_value_to_date_minor: string;
  current_variation_amount_minor: string; requested_advance_recovery_minor: string; vat_mode: "ZERO" | "AUTO_5" | "MANUAL";
  manual_vat_amount_minor: string | null; tax_invoice_received: boolean; tax_invoice_number: string | null; tax_invoice_date: string | null;
  notes: string | null; previous_certified_work_minor: string | null; current_work_amount_minor: string | null; gross_certified_minor: string | null;
  retention_bps: number | null; retention_amount_minor: string | null; advance_recovery_minor: string | null; deductions_total_minor: string | null;
  net_before_vat_minor: string | null; vat_amount_minor: string | null; payable_amount_minor: string | null; status: CertificateStatus;
  posted_journal_entry_id: string | null; reversal_journal_entry_id: string | null; created_at: string; created_by: string;
  approved_at: string | null; approved_by: string | null; reversed_at: string | null; reversed_by: string | null; reversal_reason: string | null;
}
export interface CertificateDeductionRead { id: string; company_id: string; certificate_id: string; line_number: number; deduction_type: "COMPANY_MATERIALS" | "BACKCHARGE" | "OTHER"; description: string; amount_minor: string; account_id: string; created_at: string; created_by: string; }
export interface CertificateDeductionMapping { company_id: string; deduction_type: CertificateDeductionRead["deduction_type"]; account_id: string; }
export interface CertificateReadResult { certificates: SubcontractorCertificateRead[]; deductions: CertificateDeductionRead[]; mappings: CertificateDeductionMapping[]; }
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i; const money=/^\d+$/;
const projection="id,company_id,certificate_reference,contractor_certificate_number,certificate_date,project_id,subcontractor_id,subcontract_id,work_value_to_date_minor::text,current_variation_amount_minor::text,requested_advance_recovery_minor::text,vat_mode,manual_vat_amount_minor::text,tax_invoice_received,tax_invoice_number,tax_invoice_date,notes,previous_certified_work_minor::text,current_work_amount_minor::text,gross_certified_minor::text,retention_bps,retention_amount_minor::text,advance_recovery_minor::text,deductions_total_minor::text,net_before_vat_minor::text,vat_amount_minor::text,payable_amount_minor::text,status,posted_journal_entry_id,reversal_journal_entry_id,created_at,created_by,approved_at,approved_by,reversed_at,reversed_by,reversal_reason";
const deductionProjection="id,company_id,certificate_id,line_number,deduction_type,description,amount_minor::text,account_id,created_at,created_by";
function validAmount(value: unknown, nullable=false){return nullable&&value===null||typeof value==="string"&&money.test(value)&&BigInt(value)<=9000000000000000n;}
function mapCertificate(row:any):SubcontractorCertificateRead { const base=[row.id,row.company_id,row.project_id,row.subcontractor_id,row.subcontract_id]; if(base.some(value=>!uuid.test(value))||!["DRAFT","POSTED","REVERSED"].includes(row.status)||!["ZERO","AUTO_5","MANUAL"].includes(row.vat_mode)||![row.work_value_to_date_minor,row.current_variation_amount_minor,row.requested_advance_recovery_minor].every(value=>validAmount(value))||![row.manual_vat_amount_minor,row.previous_certified_work_minor,row.current_work_amount_minor,row.gross_certified_minor,row.retention_amount_minor,row.advance_recovery_minor,row.deductions_total_minor,row.net_before_vat_minor,row.vat_amount_minor,row.payable_amount_minor].every(value=>validAmount(value,true))) throw new Error("Invalid Certificate row"); return row as SubcontractorCertificateRead; }
function mapDeduction(row:any):CertificateDeductionRead {if(!uuid.test(row.id)||!uuid.test(row.company_id)||!uuid.test(row.certificate_id)||!uuid.test(row.account_id)||!validAmount(row.amount_minor)||!["COMPANY_MATERIALS","BACKCHARGE","OTHER"].includes(row.deduction_type))throw new Error("Invalid Certificate deduction");return row as CertificateDeductionRead;}
export const canReadSubcontractorCertificates=(role:string)=>["ACCOUNTING_ADMIN","ACCOUNTANT","MANAGEMENT_VIEWER"].includes(role);
export async function readSubcontractorCertificates(client:SupabaseClient<Database>,companyId:string):Promise<CertificateReadResult>{
  if(!uuid.test(companyId))throw new Error("Invalid Certificate scope");
  const certificates:SubcontractorCertificateRead[]=[],deductions:CertificateDeductionRead[]=[];
  for(let from=0;;from+=500){const{data,error}=await client.from("subcontractor_certificates").select(projection).eq("company_id",companyId).order("certificate_date",{ascending:false}).order("id",{ascending:true}).range(from,from+499);if(error||!data)throw new Error("Certificate read unavailable");for(const row of data){if(row.company_id!==companyId)throw new Error("Invalid Certificate scope");certificates.push(mapCertificate(row));}if(data.length<500)break;}
  for(let from=0;;from+=500){const{data,error}=await client.from("subcontractor_certificate_deductions").select(deductionProjection).eq("company_id",companyId).order("certificate_id",{ascending:true}).order("line_number",{ascending:true}).range(from,from+499);if(error||!data)throw new Error("Certificate read unavailable");for(const row of data){if(row.company_id!==companyId)throw new Error("Invalid Certificate scope");deductions.push(mapDeduction(row));}if(data.length<500)break;}
  const{data:mappings,error}=await client.from("certificate_deduction_account_mappings").select("company_id,deduction_type,account_id").eq("company_id",companyId);if(error||!mappings||mappings.some(row=>row.company_id!==companyId||!uuid.test(row.account_id)||!["COMPANY_MATERIALS","BACKCHARGE","OTHER"].includes(row.deduction_type)))throw new Error("Certificate read unavailable");
  return{certificates,deductions,mappings:mappings as CertificateDeductionMapping[]};
}
export async function readSubcontractorCertificateById(client:SupabaseClient<Database>,companyId:string,id:string){if(!uuid.test(companyId)||!uuid.test(id))throw new Error("Invalid Certificate scope");const{data,error}=await client.from("subcontractor_certificates").select(projection).eq("company_id",companyId).eq("id",id).maybeSingle();if(error||!data||data.company_id!==companyId)throw new Error("Certificate readback unavailable");return mapCertificate(data);}
export async function readCertificateBySource(client:SupabaseClient<Database>,companyId:string,subcontractId:string,number:string){if(!uuid.test(companyId)||!uuid.test(subcontractId)||!number.trim())throw new Error("Invalid Certificate scope");const{data,error}=await client.from("subcontractor_certificates").select(projection).eq("company_id",companyId).eq("subcontract_id",subcontractId).eq("contractor_certificate_number",number.trim()).maybeSingle();if(error)throw new Error("Certificate recovery unavailable");return data?mapCertificate(data):null;}
export async function readCertificateDeductions(client:SupabaseClient<Database>,companyId:string,certificateId:string){if(!uuid.test(companyId)||!uuid.test(certificateId))throw new Error("Invalid Certificate scope");const{data,error}=await client.from("subcontractor_certificate_deductions").select(deductionProjection).eq("company_id",companyId).eq("certificate_id",certificateId).order("line_number",{ascending:true});if(error||!data||data.some(row=>row.company_id!==companyId))throw new Error("Certificate recovery unavailable");return data.map(mapDeduction);}
