import type { SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "../types/database.generated";
import { SupplierPaymentReverseError, normalizeSupplierPaymentReverseInput, reverseSupplierPayment, supplierPaymentReversePayload, validSupplierPaymentReverseReceipt, type SupplierPaymentReverseInput, type SupplierPaymentReverseReceipt } from "./supplierPaymentReverseRepository";
export interface SupplierPaymentReverseAttempt { version: 1; userId: string; companyId: string; paymentId: string; key: string; input: SupplierPaymentReverseInput; receipt?: SupplierPaymentReverseReceipt; }
export const supplierPaymentReverseStorageKey = (userId: string, companyId: string, paymentId: string) => `makeracc:supplier-payment-reverse:${userId}:${companyId}:${paymentId}`;
export function loadSupplierPaymentReverseAttempt(storage: Storage, userId: string, companyId: string, paymentId: string): SupplierPaymentReverseAttempt | null { const text = storage.getItem(supplierPaymentReverseStorageKey(userId, companyId, paymentId)); if (!text) return null; const value = JSON.parse(text) as SupplierPaymentReverseAttempt; if (value.version !== 1 || value.userId !== userId || value.companyId !== companyId || value.paymentId !== paymentId || (value.receipt !== undefined && !validSupplierPaymentReverseReceipt(value.receipt))) throw new Error("recovery"); const input = normalizeSupplierPaymentReverseInput(value.input); supplierPaymentReversePayload(companyId, paymentId, value.key, input); return { version: 1, userId, companyId, paymentId, key: value.key, input, ...(value.receipt ? { receipt: value.receipt } : {}) }; }
export function saveSupplierPaymentReverseAttempt(storage: Storage, attempt: SupplierPaymentReverseAttempt) { storage.setItem(supplierPaymentReverseStorageKey(attempt.userId, attempt.companyId, attempt.paymentId), JSON.stringify(attempt)); }
const inFlight = new Map<string, Promise<SupplierPaymentReverseAttempt>>();
export function sendSupplierPaymentReverseAttempt(client: SupabaseClient<Database>, storage: Storage, attempt: SupplierPaymentReverseAttempt, firstSend = false): Promise<SupplierPaymentReverseAttempt> { if (attempt.receipt) return Promise.resolve(attempt); const lock = supplierPaymentReverseStorageKey(attempt.userId, attempt.companyId, attempt.paymentId); const running = inFlight.get(lock); if (running) return running; const run = (async () => { saveSupplierPaymentReverseAttempt(storage, attempt); const { data, error } = await client.auth.getSession(); if (error || data.session?.user.id !== attempt.userId) throw new Error("denied"); let receipt: SupplierPaymentReverseReceipt; try { receipt = await reverseSupplierPayment(client, attempt.companyId, attempt.paymentId, attempt.key, attempt.input); } catch (error) { if (firstSend && error instanceof SupplierPaymentReverseError && error.rejected) { storage.removeItem(lock); throw new Error("rejected"); } throw error; } const completed = { ...attempt, receipt }; try { saveSupplierPaymentReverseAttempt(storage, completed); } catch { /* frozen request remains replayable */ } return completed; })(); inFlight.set(lock, run); void run.finally(() => { if (inFlight.get(lock) === run) inFlight.delete(lock); }).catch(() => {}); return run; }
