import type { SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "../types/database.generated";
export interface SupplierPaymentReverseInput { date: string; reason: string; }
export interface SupplierPaymentReverseReceipt { supplier_payment_id: string; payment_reference: string; reversal_journal_entry_id: string; replayed: boolean; }
const uuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
export const canReverseSupplierPayment = (role: string, status: string) => role === "ACCOUNTING_ADMIN" && status === "POSTED";
export function normalizeSupplierPaymentReverseInput(input: SupplierPaymentReverseInput) { if (!input || !/^\d{4}-\d{2}-\d{2}$/.test(input.date) || !Number.isFinite(Date.parse(input.date)) || new Date(input.date).toISOString().slice(0, 10) !== input.date || typeof input.reason !== "string") throw new Error("invalid"); const reason = input.reason.trim(); if (!reason || [...reason].length > 1000) throw new Error("invalid"); return { date: input.date, reason }; }
export function supplierPaymentReversePayload(companyId: string, paymentId: string, key: string, raw: SupplierPaymentReverseInput) { if (!uuid.test(companyId) || !uuid.test(paymentId) || !uuid.test(key)) throw new Error("invalid"); const input = normalizeSupplierPaymentReverseInput(raw); return { target_company_id: companyId, target_supplier_payment_id: paymentId, target_reversal_date: input.date, target_reason: input.reason, target_idempotency_key: key }; }
export function validSupplierPaymentReverseReceipt(value: unknown): value is SupplierPaymentReverseReceipt { if (!value || typeof value !== "object") return false; const row = value as SupplierPaymentReverseReceipt; return uuid.test(row.supplier_payment_id) && uuid.test(row.reversal_journal_entry_id) && typeof row.payment_reference === "string" && !!row.payment_reference && typeof row.replayed === "boolean"; }
export class SupplierPaymentReverseError extends Error { readonly rejected: boolean; constructor(rejected: boolean) { super("unresolved"); this.rejected = rejected; } }
export async function reverseSupplierPayment(client: SupabaseClient<Database>, companyId: string, paymentId: string, key: string, input: SupplierPaymentReverseInput): Promise<SupplierPaymentReverseReceipt> { const { data, error } = await client.rpc("reverse_supplier_payment", supplierPaymentReversePayload(companyId, paymentId, key, input)); if (error) throw new SupplierPaymentReverseError(true); if (!data || data.length !== 1 || !validSupplierPaymentReverseReceipt(data[0])) throw new SupplierPaymentReverseError(false); return data[0]; }
