export const attendanceText = {
 en: {
 title: 'Attendance', day: 'Daily exceptions', review: 'Monthly review', assignments: 'Employee site assignments',
 project: 'Project / Site', date: 'Date', employee: 'Employee', half: 'Half Day', full: 'Full Day',
 present: 'No absence exception', voided: 'Voided', note: 'Note (optional)', reason: 'Correction reason (required)',
 save: 'Save absence', correct: 'Save correction', void: 'Void absence', refresh: 'Refresh',
 loading: 'Loading attendance…', error: 'Unable to complete the request. Refresh to check the saved state before trying again.',
 denied: 'Attendance access is not available for this role.', empty: 'No eligible employees for this site and date.',
 scope: 'Record absence exceptions only. No exception means present for an eligible employee/date. All recorded absences are salary-deductible.',
 locked: 'This attendance month is locked.', month: 'Month', reviewed: 'Review confirmed', unreviewed: 'Review required',
 confirm: 'I reviewed employee assignments and absence exceptions for this month.', confirmButton: 'Confirm monthly review',
 reviewScope: 'Review confirmation is invalidated by attendance or assignment changes. Payroll is not posted here.',
 start: 'Start date', end: 'End date (optional)', assign: 'Assign employee to site', endEdit: 'Change end date',
 assignmentHint: 'One site per employee/date. To transfer, end the existing assignment before adding the next one. Assignment starts and identity cannot be edited.',
 recorded: 'Recorded by', updated: 'Last changed by', days: 'Absence days', noExceptions: 'No absence exceptions this month.',
 noAssignments: 'No employee assignments this month.', back: 'Company workspace', signOut: 'Sign out', switchCompany: 'Switch Company',
 saved: 'Saved. Attendance refreshed.', reviewDone: 'Monthly review confirmed.', select: 'Select…', utc: 'Dates use the server’s UTC calendar day.',
 history: 'Current provenance', noEmployees: 'No active EMPLOYEE Parties available. Existing employee provisioning is required.',
 },
 ar: {
 title: 'الحضور', day: 'استثناءات اليوم', review: 'المراجعة الشهرية', assignments: 'تعيينات الموظفين في المواقع',
 project: 'المشروع / الموقع', date: 'التاريخ', employee: 'الموظف', half: 'نصف يوم', full: 'يوم كامل',
 present: 'لا يوجد غياب مسجل', voided: 'ملغى', note: 'ملاحظة (اختياري)', reason: 'سبب التصحيح (مطلوب)',
 save: 'حفظ الغياب', correct: 'حفظ التصحيح', void: 'إلغاء الغياب', refresh: 'تحديث',
 loading: 'جارٍ تحميل الحضور…', error: 'تعذر إكمال الطلب. حدّث البيانات للتحقق من الحفظ قبل المحاولة مجدداً.',
 denied: 'هذه الصلاحية لا تتيح الوصول إلى الحضور.', empty: 'لا يوجد موظفون مؤهلون لهذا الموقع والتاريخ.',
 scope: 'سجّل الغياب فقط. عدم وجود غياب يعني الحضور للموظف المؤهل في التاريخ. جميع حالات الغياب المسجلة تخصم من الراتب.',
 locked: 'شهر الحضور مقفل.', month: 'الشهر', reviewed: 'تم تأكيد المراجعة', unreviewed: 'المراجعة مطلوبة',
 confirm: 'راجعت تعيينات الموظفين وحالات الغياب لهذا الشهر.', confirmButton: 'تأكيد المراجعة الشهرية',
 reviewScope: 'تتطلب تغييرات الحضور أو التعيينات مراجعة جديدة. لا يتم ترحيل الرواتب هنا.',
 start: 'تاريخ البداية', end: 'تاريخ النهاية (اختياري)', assign: 'تعيين الموظف في الموقع', endEdit: 'تغيير تاريخ النهاية',
 assignmentHint: 'موقع واحد لكل موظف في اليوم. للنقل، أنهِ التعيين الحالي قبل إضافة التالي. لا يمكن تعديل بداية التعيين أو هويته.',
 recorded: 'سجّله', updated: 'آخر تعديل بواسطة', days: 'أيام الغياب', noExceptions: 'لا توجد حالات غياب لهذا الشهر.',
 noAssignments: 'لا توجد تعيينات موظفين لهذا الشهر.', back: 'مساحة عمل الشركة', signOut: 'تسجيل الخروج', switchCompany: 'تغيير الشركة',
 saved: 'تم الحفظ وتحديث الحضور.', reviewDone: 'تم تأكيد المراجعة الشهرية.', select: 'اختر…', utc: 'تعتمد التواريخ على يوم الخادم بتوقيت UTC.',
 history: 'بيانات التسجيل والتعديل', noEmployees: 'لا توجد أطراف نشطة من نوع موظف. يلزم تجهيز الموظفين عبر المسار الحالي.',
 },
};
export type AttendanceLabels = typeof attendanceText.en;
