import {ReportExport} from '../reports/ReportExport';
import {sourceReport} from '../reports/sourceReports';
import type {DashboardSummary} from '../dashboard/dashboardSummary';
import {useState} from 'react';
import {useI18n} from '../i18n/I18nContext';
import {DashboardChart} from '../dashboard/DashboardChart';
import {Badge} from '../components/ui/Badge';
import {minorDisplay,sourceCurrentAmount,sourceDirection,sourceAccounting,sourceReportingMonth,type ReportingBasis,sourceValue,sourceTotals,type SourceRecord} from './sourceModel';
export function HistoricalOverview({rows,loading,error,refresh,company,postedSummary}:{rows:SourceRecord[];loading:boolean;error:boolean;refresh:()=>void;company:string;postedSummary?:DashboardSummary|null}) {
 const {locale}=useI18n(),ar=locale==='ar';const [basis,setBasis]=useState<ReportingBasis>('SOURCE');const totals=sourceTotals(rows);
 const generalMonths=[...new Set(rows.filter(r=>r.record_type==='GENERAL').map(r=>sourceReportingMonth(r,basis)))].sort();
 const months=generalMonths.slice(-2);const payrollMonth=[...new Set(rows.filter(r=>r.record_type==='PAYROLL').map(r=>sourceReportingMonth(r,basis)))].sort().at(-1);
 const monthName=(m:string)=>new Intl.DateTimeFormat(ar?'ar-AE':'en-GB',{month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(m+'-01T00:00:00Z'));
 const sum=(rs:SourceRecord[],field:'outflow_minor'|'payroll_net_minor')=>rs.reduce((n,r)=>n+BigInt(r[field]??'0'),0n).toString();
 const corrected=(rs:SourceRecord[])=>rs.filter(r=>r.review_status!=='CANCELLED').reduce((n,r)=>n+BigInt(sourceCurrentAmount(r)??'0'),0n).toString();
 const cards=months.map(m=>({label:`${monthName(m)} · ${ar?'الصرف النقدي':'Cash outflow'}`,original:sum(rows.filter(r=>r.record_type==='GENERAL'&&sourceReportingMonth(r,basis)===m),'outflow_minor'),current:corrected(rows.filter(r=>r.record_type==='GENERAL'&&sourceReportingMonth(r,basis)===m&&sourceDirection(r)==='OUT'))}));
 cards.push({label:ar?'إجمالي الصرف التاريخي':'Total historical cash outflow',original:totals.originalOut,current:totals.correctedOut});
 cards.push({label:`${payrollMonth?monthName(payrollMonth):''} · ${ar?'صافي رواتب المصدر':'Net source Payroll'}`,original:sum(rows.filter(r=>r.record_type==='PAYROLL'&&sourceReportingMonth(r,basis)===payrollMonth),'payroll_net_minor'),current:corrected(rows.filter(r=>r.record_type==='PAYROLL'&&sourceReportingMonth(r,basis)===payrollMonth))});
 const groups=new Map<string,bigint>();for(const r of rows.filter(r=>r.record_type==='GENERAL'&&r.review_status!=='CANCELLED'&&sourceDirection(r)==='OUT')){const category=sourceValue(r,'category',r.classification.category_proposal)|| (ar?'غير مصنف':'Unclassified');groups.set(category,(groups.get(category)??0n)+BigInt(sourceCurrentAmount(r)??'0'));}
 const categories=[...groups].map(([id,minor])=>({id,label:id,minor:minor.toString()})).sort((a,b)=>BigInt(a.minor)>BigInt(b.minor)?-1:1);
 const statuses=new Map<string,number>();for(const r of rows){const s=r.review_status==='CANCELLED'?'ARCHIVED':sourceAccounting(r);statuses.set(s,(statuses.get(s)??0)+1);}
 return <section className="min-w-0 space-y-4" dir={ar?'rtl':'ltr'} aria-label={ar?'النظرة المالية':'Financial Overview'}>
  <header className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-2xl font-semibold text-slate-900">{ar?'النظرة المالية':'Financial Overview'}</h2><p className="mt-1 text-sm leading-6 text-slate-500">{ar?'الحركة التاريخية الفعلية من بيانات المصدر، منفصلة عن الأرصدة المحاسبية المرحلة.':'Actual historical source activity, separate from posted accounting balances.'}</p></div><button className="rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm disabled:opacity-50" disabled={loading} onClick={refresh}>{ar?'تحديث':'Refresh historical activity'}</button></header>
  <ReportExport disabled={loading||error} build={()=>sourceReport(rows,company,locale,basis,'OVERVIEW',generalMonths.join(', '),postedSummary)}/>
  <label className="block max-w-md text-sm text-slate-600">{ar?'أساس الشهر (موحد للأصلي والمصحح)':'Month basis (same for original and corrected)'}<select aria-label={ar?'أساس شهر التقرير':'Reporting month basis'} className="mt-1 block w-full rounded-lg border border-slate-300 bg-white p-2" value={basis} onChange={e=>setBasis(e.target.value as ReportingBasis)}><option value="SOURCE">{ar?'شهر المصدر المستورد':'Imported source month'}</option><option value="DATE">{ar?'شهر تاريخ المعاملة / الراتب المصحح':'Transaction date / corrected salary month'}</option></select></label>
  <p className="text-xs text-slate-500">{ar?'تستخدم المقارنة نفس السجلات ونفس أساس الشهر؛ الأرشفة وتصحيح المبلغ وحدهما يغيران الإجمالي النشط.':'Comparisons use the same records and month basis. Archiving and amount corrections change active totals; source evidence is preserved.'}</p>
  {loading&&<p role="status" className="rounded-lg bg-blue-50 p-3 text-sm text-blue-800">{ar?'جار تحميل النشاط المالي':'Loading financial activity…'}</p>}
  {error&&<p role="alert" className="rounded-lg border border-red-200 bg-red-50 p-4 text-red-800">{ar?'تعذر تحميل النشاط التاريخي. أعد المحاولة.':'Historical activity could not be loaded. Try refreshing.'}</p>}
  {!error&&<><div className="grid min-w-0 gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(c=><article key={c.label} style={{borderTopColor:"var(--tenant-primary, #2563eb)"}} className="min-w-0 rounded-xl border border-slate-200 border-t-4 bg-white p-5 shadow-sm"><h3 className="text-sm font-medium text-slate-600">{c.label}</h3><p className="mt-3 break-words text-2xl font-semibold tabular-nums text-slate-900"><bdi dir="ltr">{loading&&rows.length===0?'—':minorDisplay(c.original)} <span className="text-sm font-normal">AED</span></bdi></p><p className="mt-1 text-xs text-slate-500">{ar?'الإجمالي المستورد الأصلي':'Original imported total'}</p><div className="mt-4 border-t border-slate-100 pt-3 text-sm"><p>{ar?'الإجمالي المصحح النشط':'Corrected active total'}</p><p className="mt-1 font-semibold tabular-nums"><bdi dir="ltr">{loading&&rows.length===0?'—':minorDisplay(c.current)} AED</bdi></p>{c.current!==c.original&&<p className="mt-1 text-xs text-amber-800">{ar?'الفرق':'Difference'}: <bdi dir="ltr">{minorDisplay((BigInt(c.current)-BigInt(c.original)).toString())} AED</bdi></p>}</div></article>)}</div>
  <div className="flex flex-wrap gap-3 text-sm"><Badge tone="blue">{totals.general} {ar?'حركة مالية':'General financial records'}</Badge><Badge tone="blue">{totals.payroll} {ar?'سجل راتب':'Payroll records'}</Badge><Badge>{totals.total} {ar?'سجل مستورد':'total imported records'}</Badge><Badge tone="green">{totals.active} {ar?'سجل نشط':'active records'}</Badge></div>
  <p className="rounded-lg border border-slate-200 bg-white p-4 text-sm leading-6 text-slate-600">{ar?'الوارد النقدي الأصلي / المصحح النشط':'Cash inflows · original / corrected active'}: <bdi dir="ltr" className="font-medium tabular-nums">{minorDisplay(totals.originalIn)} / {minorDisplay(totals.correctedIn)} AED</bdi>. {ar?'صافي الرواتب أساس مستقل؛ لا يضاف إلى إجمالي الصرف. الحذف يستبعد السجل من المراجعة النشطة ولا يلغي الدفع النقدي الفعلي.':'Payroll net is a separate basis; do not add it to cash outflow. Archiving removes a record from active review without undoing its actual cash movement.'}</p>
  <div className="grid min-w-0 gap-4 lg:grid-cols-2"><div className="rounded-xl border border-slate-200 bg-white p-5"><h3 className="font-semibold">{ar?'الصرف حسب الشهر':'Cash outflow by month'}</h3><div className="mt-3 space-y-3">{generalMonths.map(m=><div key={m} className="flex flex-wrap justify-between gap-2 border-b border-slate-100 pb-3 text-sm"><span>{monthName(m)}</span><bdi dir="ltr" className="tabular-nums">{minorDisplay(sum(rows.filter(r=>r.record_type==='GENERAL'&&sourceReportingMonth(r,basis)===m),'outflow_minor'))} AED</bdi></div>)}</div><h3 className="mt-5 font-semibold">{ar?'حالة المعالجة':'Processing status'}</h3><div className="mt-3 flex flex-wrap gap-2">{[...statuses].map(([s,n])=><Badge key={s} tone={s==='POSTED'?'green':s==='ARCHIVED'?'red':'slate'}>{s==='ARCHIVED'?(ar?'مؤرشف':'Archived'):s==='POSTED'?(ar?'مرحل':'Posted'):s==='LINKED'?(ar?'مرتبط بالمحاسبة':'Canonical Payroll link'):s==='REVERSED'?(ar?'معكوس':'Reversed'):s==='DRAFT'?(ar?'مسودة':'Draft'):(ar?'يحتاج استكمال':'Needs completion')}: {n}</Badge>)}</div></div><DashboardChart title={ar?'الصرف النشط حسب فئة المراجعة':'Active outflow by review category'} subtitle={ar?'حركات نقدية مصححة، وليست تكاليف مرحلة':'Corrected cash movements, not posted costs'} groups={categories}/></div></>}
 </section>;
}
