import {sourceDirection,sourceLinked,sourceValue,type SourceRecord} from './sourceModel';
export function sourceExpenseCandidate(r:SourceRecord){return r.record_type==='GENERAL'&&r.review_status!=='CANCELLED'&&!sourceLinked(r)&&sourceDirection(r)==='OUT'&&sourceValue(r,'nature',r.classification.nature)==='EXPENSE';}
export function sourceWorkflow(r:SourceRecord):{path:string|null;en:string;ar:string;missingEn:string;missingAr:string}{
 const n=sourceValue(r,'nature',r.classification.nature);
 if(n==='PAYROLL_OR_SALARY_PAYMENT')return {path:'/payroll?view=register&month='+encodeURIComponent(r.source_month),en:'Open salary settlement',ar:'فتح تسوية الرواتب',missingEn:'Confirm the actual earning period (the cash payment month does not prove it), then select the verified Employee and existing posted salary entitlement, confirm actual payment date/reference and MAIN_CASH. Do not pay the source Payroll net again if this cash payment already settles it.',missingAr:'اختر الموظف المعتمد واستحقاق الراتب المرحل، وأكد تاريخ الدفع ومرجعه وMAIN_CASH. لا تدفع صافي المصدر مرة أخرى إذا تمت تسويته بهذه الحركة.'};
 if(n==='SUPPLIER_PAYMENT')return {path:'/supplier-payments',en:'Open supplier settlement',ar:'فتح تسوية المورد',missingEn:'Match the existing supplier liability/Expense, actual payment date, amount and MAIN_CASH. Do not recognize the cost again.',missingAr:'طابق التزام المورد / المصروف السابق وتاريخ الدفع والمبلغ وMAIN_CASH. لا تسجل التكلفة مرة أخرى.'};
 if(n==='SUPPLIER_INVOICE_OR_COMMITMENT')return {path:'/expenses#supplier-credit',en:'Review supplier invoice',ar:'مراجعة فاتورة المورد',missingEn:'Confirm this is a recognized supplier invoice rather than a commitment; complete supplier, category, Project/overhead, invoice and VAT evidence in the existing Supplier Credit Expense flow.',missingAr:'أكد أنها فاتورة معترف بها وليست التزاماً فقط؛ استكمل المورد والفئة والمشروع / الشركة وأدلة الفاتورة والضريبة في مسار المصروف الآجل.'};
 if(n==='EMPLOYEE_ADVANCE')return {path:null,en:'Complete employee advance',ar:'استكمال سلفة الموظف',missingEn:'Verified Employee, receivable policy/account and supported employee-advance command are required. Custody Advances are not interchangeable with salary advances.',missingAr:'يلزم موظف معتمد وسياسة وحساب ذمم ومسار سلفة موظف مدعوم. سلف العهد ليست بديلاً عن سلف الرواتب.'};
 if(n==='TREASURY_INFLOW_OR_FUNDING')return {path:null,en:'Complete cash funding',ar:'استكمال التمويل النقدي',missingEn:'Confirm the actual payer and funding nature (owner capital/loan, receivable receipt or transfer). A generic funding/receipt command is not currently available; no offset or opening balance is invented.',missingAr:'أكد الدافع الفعلي وطبيعة التمويل (رأس مال / قرض / تحصيل ذمم / تحويل). لا يوجد أمر تمويل / قبض عام حالياً؛ لا ينشأ حساب مقابل أو رصيد افتتاحي مفترض.'};
 if(n==='REFUNDABLE_DEPOSIT')return {path:null,en:'Complete refundable deposit',ar:'استكمال التأمين المسترد',missingEn:'Confirm beneficiary, deposit receivable and recovery conditions. A supported refundable-deposit command is required; this is not an operating expense.',missingAr:'أكد المستفيد وذمة التأمين وشروط الاسترداد. يلزم مسار تأمين مسترد مدعوم؛ ليس مصروفاً تشغيلياً.'};
 if(n==='OWNER_PARTNER_DRAWING_OR_ADVANCE'||n==='PARTNER_TRANSFER_OR_ADVANCE')return {path:null,en:'Complete owner/partner movement',ar:'استكمال حركة الشريك',missingEn:'Confirm whether this is a drawing, receivable advance or actual transfer and supply the relevant counterparty and accounts. A dedicated command is not currently available.',missingAr:'حدد هل هي مسحوبات أو سلفة مدينة أو تحويل فعلي، مع الطرف والحسابات المطلوبة. لا يوجد أمر متخصص حالياً.'};
 return {path:null,en:'Complete accounting review',ar:'استكمال المراجعة المحاسبية',missingEn:'Confirm the actual transaction nature, beneficiary and recognition/settlement evidence. Select the correct supported workflow after completing the source review.',missingAr:'أكد نوع المعاملة الفعلي والمستفيد وأدلة الاعتراف / التسوية، ثم اختر المسار المدعوم بعد استكمال المراجعة.'};
}
