-- Fixture/Auth cleanup complete; retained historical support. See README.md.
-- MakerACC-Development (eqnzueginpkskbnqvgoc) ONLY. Operational fixture; NOT a migration.
-- Execute once. Stops on any collision; no upsert or random replacement.
begin;
do $fixture$
declare r record; n bigint;
begin
  perform id from auth.users where id='9dbcfe8d-0333-4d3c-8b1b-3acc4b9b47d3' for update;
  perform user_id from public.profiles where user_id='9dbcfe8d-0333-4d3c-8b1b-3acc4b9b47d3' for update;
  if (select count(*) from auth.users where id='9dbcfe8d-0333-4d3c-8b1b-3acc4b9b47d3' and email='p6c-slice4-user@example.test')<>1
    or (select count(*) from auth.users where id='9dbcfe8d-0333-4d3c-8b1b-3acc4b9b47d3' or lower(email)='p6c-slice4-user@example.test')<>1
    or (select count(*) from public.profiles where user_id='9dbcfe8d-0333-4d3c-8b1b-3acc4b9b47d3' and email_snapshot='p6c-slice4-user@example.test' and status='ACTIVE')<>1
    then raise exception 'Exact synthetic Auth/profile identity mismatch'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='companies' and column_name='id' and udt_name='uuid' and is_nullable='NO') then raise exception 'Fixture column mismatch: companies.id'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='companies' and column_name='code' and udt_name='text' and is_nullable='NO') then raise exception 'Fixture column mismatch: companies.code'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='companies' and column_name='name' and udt_name='text' and is_nullable='NO') then raise exception 'Fixture column mismatch: companies.name'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='companies' and column_name='status' and udt_name='account_status' and is_nullable='NO') then raise exception 'Fixture column mismatch: companies.status'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='companies' and column_name='created_at' and udt_name='timestamptz' and is_nullable='NO') then raise exception 'Fixture column mismatch: companies.created_at'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='companies' and column_name='updated_at' and udt_name='timestamptz' and is_nullable='NO') then raise exception 'Fixture column mismatch: companies.updated_at'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='companies' and column_name='legal_name' and udt_name='text' and is_nullable='YES') then raise exception 'Fixture column mismatch: companies.legal_name'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='companies' and column_name='trn' and udt_name='text' and is_nullable='YES') then raise exception 'Fixture column mismatch: companies.trn'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='companies' and column_name='address' and udt_name='text' and is_nullable='YES') then raise exception 'Fixture column mismatch: companies.address'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='companies' and column_name='notes' and udt_name='text' and is_nullable='YES') then raise exception 'Fixture column mismatch: companies.notes'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='companies' and column_name='created_by' and udt_name='uuid' and is_nullable='YES') then raise exception 'Fixture column mismatch: companies.created_by'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='companies' and column_name='updated_by' and udt_name='uuid' and is_nullable='YES') then raise exception 'Fixture column mismatch: companies.updated_by'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='company_memberships' and column_name='id' and udt_name='uuid' and is_nullable='NO') then raise exception 'Fixture column mismatch: company_memberships.id'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='company_memberships' and column_name='company_id' and udt_name='uuid' and is_nullable='NO') then raise exception 'Fixture column mismatch: company_memberships.company_id'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='company_memberships' and column_name='user_id' and udt_name='uuid' and is_nullable='NO') then raise exception 'Fixture column mismatch: company_memberships.user_id'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='company_memberships' and column_name='role' and udt_name='company_role' and is_nullable='NO') then raise exception 'Fixture column mismatch: company_memberships.role'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='company_memberships' and column_name='status' and udt_name='account_status' and is_nullable='NO') then raise exception 'Fixture column mismatch: company_memberships.status'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='company_memberships' and column_name='created_at' and udt_name='timestamptz' and is_nullable='NO') then raise exception 'Fixture column mismatch: company_memberships.created_at'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='company_memberships' and column_name='created_by' and udt_name='uuid' and is_nullable='YES') then raise exception 'Fixture column mismatch: company_memberships.created_by'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='company_memberships' and column_name='updated_at' and udt_name='timestamptz' and is_nullable='NO') then raise exception 'Fixture column mismatch: company_memberships.updated_at'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='company_memberships' and column_name='updated_by' and udt_name='uuid' and is_nullable='YES') then raise exception 'Fixture column mismatch: company_memberships.updated_by'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='company_settings' and column_name='company_id' and udt_name='uuid' and is_nullable='NO') then raise exception 'Fixture column mismatch: company_settings.company_id'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='company_settings' and column_name='tenant_slug' and udt_name='text' and is_nullable='NO') then raise exception 'Fixture column mismatch: company_settings.tenant_slug'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='company_settings' and column_name='app_display_name' and udt_name='text' and is_nullable='YES') then raise exception 'Fixture column mismatch: company_settings.app_display_name'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='company_settings' and column_name='default_locale' and udt_name='app_locale' and is_nullable='NO') then raise exception 'Fixture column mismatch: company_settings.default_locale'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='company_settings' and column_name='logo_url' and udt_name='text' and is_nullable='YES') then raise exception 'Fixture column mismatch: company_settings.logo_url'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='company_settings' and column_name='favicon_url' and udt_name='text' and is_nullable='YES') then raise exception 'Fixture column mismatch: company_settings.favicon_url'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='company_settings' and column_name='primary_color' and udt_name='text' and is_nullable='NO') then raise exception 'Fixture column mismatch: company_settings.primary_color'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='company_settings' and column_name='accent_color' and udt_name='text' and is_nullable='NO') then raise exception 'Fixture column mismatch: company_settings.accent_color'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='company_settings' and column_name='created_at' and udt_name='timestamptz' and is_nullable='NO') then raise exception 'Fixture column mismatch: company_settings.created_at'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='company_settings' and column_name='created_by' and udt_name='uuid' and is_nullable='YES') then raise exception 'Fixture column mismatch: company_settings.created_by'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='company_settings' and column_name='updated_at' and udt_name='timestamptz' and is_nullable='NO') then raise exception 'Fixture column mismatch: company_settings.updated_at'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='company_settings' and column_name='updated_by' and udt_name='uuid' and is_nullable='YES') then raise exception 'Fixture column mismatch: company_settings.updated_by'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='parties' and column_name='id' and udt_name='uuid' and is_nullable='NO') then raise exception 'Fixture column mismatch: parties.id'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='parties' and column_name='company_id' and udt_name='uuid' and is_nullable='NO') then raise exception 'Fixture column mismatch: parties.company_id'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='parties' and column_name='type' and udt_name='party_type' and is_nullable='NO') then raise exception 'Fixture column mismatch: parties.type'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='parties' and column_name='name' and udt_name='text' and is_nullable='NO') then raise exception 'Fixture column mismatch: parties.name'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='parties' and column_name='code' and udt_name='text' and is_nullable='YES') then raise exception 'Fixture column mismatch: parties.code'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='parties' and column_name='trn' and udt_name='text' and is_nullable='YES') then raise exception 'Fixture column mismatch: parties.trn'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='parties' and column_name='contact_person' and udt_name='text' and is_nullable='YES') then raise exception 'Fixture column mismatch: parties.contact_person'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='parties' and column_name='phone' and udt_name='text' and is_nullable='YES') then raise exception 'Fixture column mismatch: parties.phone'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='parties' and column_name='email' and udt_name='text' and is_nullable='YES') then raise exception 'Fixture column mismatch: parties.email'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='parties' and column_name='address' and udt_name='text' and is_nullable='YES') then raise exception 'Fixture column mismatch: parties.address'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='parties' and column_name='status' and udt_name='account_status' and is_nullable='NO') then raise exception 'Fixture column mismatch: parties.status'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='parties' and column_name='notes' and udt_name='text' and is_nullable='YES') then raise exception 'Fixture column mismatch: parties.notes'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='parties' and column_name='created_at' and udt_name='timestamptz' and is_nullable='NO') then raise exception 'Fixture column mismatch: parties.created_at'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='parties' and column_name='created_by' and udt_name='uuid' and is_nullable='YES') then raise exception 'Fixture column mismatch: parties.created_by'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='parties' and column_name='updated_at' and udt_name='timestamptz' and is_nullable='NO') then raise exception 'Fixture column mismatch: parties.updated_at'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='parties' and column_name='updated_by' and udt_name='uuid' and is_nullable='YES') then raise exception 'Fixture column mismatch: parties.updated_by'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='project_assignments' and column_name='id' and udt_name='uuid' and is_nullable='NO') then raise exception 'Fixture column mismatch: project_assignments.id'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='project_assignments' and column_name='company_id' and udt_name='uuid' and is_nullable='NO') then raise exception 'Fixture column mismatch: project_assignments.company_id'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='project_assignments' and column_name='project_id' and udt_name='uuid' and is_nullable='NO') then raise exception 'Fixture column mismatch: project_assignments.project_id'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='project_assignments' and column_name='user_id' and udt_name='uuid' and is_nullable='NO') then raise exception 'Fixture column mismatch: project_assignments.user_id'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='project_assignments' and column_name='status' and udt_name='account_status' and is_nullable='NO') then raise exception 'Fixture column mismatch: project_assignments.status'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='project_assignments' and column_name='created_at' and udt_name='timestamptz' and is_nullable='NO') then raise exception 'Fixture column mismatch: project_assignments.created_at'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='project_assignments' and column_name='created_by' and udt_name='uuid' and is_nullable='YES') then raise exception 'Fixture column mismatch: project_assignments.created_by'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='project_assignments' and column_name='updated_at' and udt_name='timestamptz' and is_nullable='NO') then raise exception 'Fixture column mismatch: project_assignments.updated_at'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='project_assignments' and column_name='updated_by' and udt_name='uuid' and is_nullable='YES') then raise exception 'Fixture column mismatch: project_assignments.updated_by'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='projects' and column_name='id' and udt_name='uuid' and is_nullable='NO') then raise exception 'Fixture column mismatch: projects.id'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='projects' and column_name='company_id' and udt_name='uuid' and is_nullable='NO') then raise exception 'Fixture column mismatch: projects.company_id'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='projects' and column_name='code' and udt_name='text' and is_nullable='NO') then raise exception 'Fixture column mismatch: projects.code'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='projects' and column_name='name' and udt_name='text' and is_nullable='NO') then raise exception 'Fixture column mismatch: projects.name'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='projects' and column_name='client_name' and udt_name='text' and is_nullable='YES') then raise exception 'Fixture column mismatch: projects.client_name'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='projects' and column_name='location' and udt_name='text' and is_nullable='YES') then raise exception 'Fixture column mismatch: projects.location'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='projects' and column_name='contract_number' and udt_name='text' and is_nullable='YES') then raise exception 'Fixture column mismatch: projects.contract_number'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='projects' and column_name='original_contract_value_minor' and udt_name='int8' and is_nullable='YES') then raise exception 'Fixture column mismatch: projects.original_contract_value_minor'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='projects' and column_name='budget_minor' and udt_name='int8' and is_nullable='YES') then raise exception 'Fixture column mismatch: projects.budget_minor'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='projects' and column_name='start_date' and udt_name='date' and is_nullable='YES') then raise exception 'Fixture column mismatch: projects.start_date'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='projects' and column_name='expected_completion_date' and udt_name='date' and is_nullable='YES') then raise exception 'Fixture column mismatch: projects.expected_completion_date'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='projects' and column_name='status' and udt_name='project_status' and is_nullable='NO') then raise exception 'Fixture column mismatch: projects.status'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='projects' and column_name='notes' and udt_name='text' and is_nullable='YES') then raise exception 'Fixture column mismatch: projects.notes'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='projects' and column_name='created_at' and udt_name='timestamptz' and is_nullable='NO') then raise exception 'Fixture column mismatch: projects.created_at'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='projects' and column_name='created_by' and udt_name='uuid' and is_nullable='YES') then raise exception 'Fixture column mismatch: projects.created_by'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='projects' and column_name='updated_at' and udt_name='timestamptz' and is_nullable='NO') then raise exception 'Fixture column mismatch: projects.updated_at'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='projects' and column_name='updated_by' and udt_name='uuid' and is_nullable='YES') then raise exception 'Fixture column mismatch: projects.updated_by'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='subcontracts' and column_name='id' and udt_name='uuid' and is_nullable='NO') then raise exception 'Fixture column mismatch: subcontracts.id'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='subcontracts' and column_name='company_id' and udt_name='uuid' and is_nullable='NO') then raise exception 'Fixture column mismatch: subcontracts.company_id'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='subcontracts' and column_name='project_id' and udt_name='uuid' and is_nullable='NO') then raise exception 'Fixture column mismatch: subcontracts.project_id'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='subcontracts' and column_name='subcontractor_id' and udt_name='uuid' and is_nullable='NO') then raise exception 'Fixture column mismatch: subcontracts.subcontractor_id'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='subcontracts' and column_name='contract_number' and udt_name='text' and is_nullable='NO') then raise exception 'Fixture column mismatch: subcontracts.contract_number'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='subcontracts' and column_name='scope_of_work' and udt_name='text' and is_nullable='NO') then raise exception 'Fixture column mismatch: subcontracts.scope_of_work'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='subcontracts' and column_name='original_contract_value_minor' and udt_name='int8' and is_nullable='NO') then raise exception 'Fixture column mismatch: subcontracts.original_contract_value_minor'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='subcontracts' and column_name='approved_variations_minor' and udt_name='int8' and is_nullable='NO') then raise exception 'Fixture column mismatch: subcontracts.approved_variations_minor'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='subcontracts' and column_name='retention_bps' and udt_name='int4' and is_nullable='NO') then raise exception 'Fixture column mismatch: subcontracts.retention_bps'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='subcontracts' and column_name='start_date' and udt_name='date' and is_nullable='YES') then raise exception 'Fixture column mismatch: subcontracts.start_date'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='subcontracts' and column_name='expected_end_date' and udt_name='date' and is_nullable='YES') then raise exception 'Fixture column mismatch: subcontracts.expected_end_date'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='subcontracts' and column_name='status' and udt_name='subcontract_status' and is_nullable='NO') then raise exception 'Fixture column mismatch: subcontracts.status'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='subcontracts' and column_name='notes' and udt_name='text' and is_nullable='YES') then raise exception 'Fixture column mismatch: subcontracts.notes'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='subcontracts' and column_name='created_at' and udt_name='timestamptz' and is_nullable='NO') then raise exception 'Fixture column mismatch: subcontracts.created_at'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='subcontracts' and column_name='created_by' and udt_name='uuid' and is_nullable='YES') then raise exception 'Fixture column mismatch: subcontracts.created_by'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='subcontracts' and column_name='updated_at' and udt_name='timestamptz' and is_nullable='NO') then raise exception 'Fixture column mismatch: subcontracts.updated_at'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='subcontracts' and column_name='updated_by' and udt_name='uuid' and is_nullable='YES') then raise exception 'Fixture column mismatch: subcontracts.updated_by'; end if;
  for r in select n.nspname,c.relname,x.attname from pg_class c join pg_namespace n on n.oid=c.relnamespace join pg_attribute x on x.attrelid=c.oid
    where n.nspname in ('public','private') and c.relkind in ('r','p') and x.attnum>0 and not x.attisdropped and x.atttypid='uuid'::regtype
  loop
    execute format('select count(*) from %I.%I where %I::text like $1',r.nspname,r.relname,r.attname) into n using '74000000-0000-4000-8000-%';
    if n<>0 then raise exception 'Slice 4 namespace collision in %.%.%',r.nspname,r.relname,r.attname; end if;
  end loop;
  if exists (select 1 from public.companies where lower(btrim(code)) like 'p6c-s4-%' or name like 'P6C Slice 4%')
    or exists (select 1 from public.company_settings where tenant_slug like 'p6c-s4-%')
    or exists (select 1 from public.projects where lower(btrim(code)) like 'p6c-s4-%')
    or exists (select 1 from public.parties where lower(btrim(code)) like 'p6c-s4-%')
    or exists (select 1 from public.subcontracts where lower(btrim(contract_number)) like 'p6c-s4-%')
    or exists (select 1 from public.company_memberships where user_id='9dbcfe8d-0333-4d3c-8b1b-3acc4b9b47d3')
    or exists (select 1 from public.project_assignments where user_id='9dbcfe8d-0333-4d3c-8b1b-3acc4b9b47d3')
    or exists (select 1 from private.system_administrators where user_id='9dbcfe8d-0333-4d3c-8b1b-3acc4b9b47d3')
    then raise exception 'Fixture code/slug/number/user collision'; end if;
  if (select count(*) from public.companies)<>14 or (select count(*) from public.company_settings)<>14 then raise exception 'Expected 14/14 baseline changed'; end if;
  if exists (select 1 from public.companies c full join public.company_settings s on s.company_id=c.id where c.id is null or s.company_id is null) then raise exception 'Company/settings one-to-one mismatch'; end if;
  insert into public.companies (id,code,name,legal_name,status,notes,created_by,updated_by) values
    ('74000000-0000-4000-8000-0000000000a1','P6C-S4-ALPHA','P6C Slice 4 Alpha','P6C Slice 4 Alpha Synthetic LLC','ACTIVE','Temporary P6C Slice 4 verification only',null,null),
    ('74000000-0000-4000-8000-0000000000a2','P6C-S4-BETA','P6C Slice 4 Beta','P6C Slice 4 Beta Synthetic LLC','ACTIVE','Temporary P6C Slice 4 verification only',null,null);
  insert into public.company_settings (company_id,tenant_slug,app_display_name,default_locale,primary_color,accent_color,created_by,updated_by) values
    ('74000000-0000-4000-8000-0000000000a1','p6c-s4-alpha','P6C S4 Alpha','en','#1d4ed8','#0891b2',null,null),
    ('74000000-0000-4000-8000-0000000000a2','p6c-s4-beta','P6C S4 Beta','ar','#7e22ce','#c2410c',null,null);
  insert into public.company_memberships (id,company_id,user_id,role,status,created_by,updated_by) values
    ('74000000-0000-4000-8000-0000000000b1','74000000-0000-4000-8000-0000000000a1','9dbcfe8d-0333-4d3c-8b1b-3acc4b9b47d3','MANAGEMENT_VIEWER','ACTIVE',null,null),
    ('74000000-0000-4000-8000-0000000000b2','74000000-0000-4000-8000-0000000000a2','9dbcfe8d-0333-4d3c-8b1b-3acc4b9b47d3','MANAGEMENT_VIEWER','ACTIVE',null,null);
  insert into public.projects (id,company_id,code,name,status,created_by,updated_by) values
    ('74000000-0000-4000-8000-0000000000c1','74000000-0000-4000-8000-0000000000a1','P6C-S4-PROJECT-A','P6C Slice 4 Project A — المشروع أ','ACTIVE',null,null),
    ('74000000-0000-4000-8000-0000000000c2','74000000-0000-4000-8000-0000000000a1','P6C-S4-PROJECT-B','P6C Slice 4 Project B — المشروع ب','ACTIVE',null,null);
  insert into public.project_assignments (id,company_id,project_id,user_id,status,created_by,updated_by) values
    ('74000000-0000-4000-8000-0000000000d1','74000000-0000-4000-8000-0000000000a1','74000000-0000-4000-8000-0000000000c1','9dbcfe8d-0333-4d3c-8b1b-3acc4b9b47d3','ACTIVE',null,null);
  insert into public.parties (id,company_id,type,code,name,status,created_by,updated_by) values
    ('74000000-0000-4000-8000-0000000000e1','74000000-0000-4000-8000-0000000000a1','SUBCONTRACTOR','P6C-S4-SUB-001','P6C S4 Concrete — مقاول الخرسانة','ACTIVE',null,null),
    ('74000000-0000-4000-8000-0000000000e2','74000000-0000-4000-8000-0000000000a1','SUBCONTRACTOR','P6C-S4-SUB-002','P6C S4 Finishes — مقاول التشطيبات','ACTIVE',null,null);
  insert into public.subcontracts (id,company_id,project_id,subcontractor_id,contract_number,scope_of_work,original_contract_value_minor,approved_variations_minor,retention_bps,start_date,expected_end_date,status,notes,created_by,updated_by) values
    ('74000000-0000-4000-8000-0000000000f1','74000000-0000-4000-8000-0000000000a1','74000000-0000-4000-8000-0000000000c1','74000000-0000-4000-8000-0000000000e1','P6C-S4-A-001','Synthetic concrete works — أعمال الخرسانة',12500000,250000,500,'2026-01-15','2026-12-31','ACTIVE','Synthetic dated contract — ملاحظة تحقق',null,null),
    ('74000000-0000-4000-8000-0000000000f2','74000000-0000-4000-8000-0000000000a1','74000000-0000-4000-8000-0000000000c1','74000000-0000-4000-8000-0000000000e1','P6C-S4-A-002','Synthetic BIGINT precision verification only',9007199254740993,0,1000,null,null,'COMPLETED',null,null,null),
    ('74000000-0000-4000-8000-0000000000f3','74000000-0000-4000-8000-0000000000a1','74000000-0000-4000-8000-0000000000c2','74000000-0000-4000-8000-0000000000e2','P6C-S4-B-001','Synthetic finishes — أعمال التشطيبات',800000,-10000,125,'2026-02-01',null,'CLOSED',null,null,null);
  if (select count(*) from auth.users where id='9dbcfe8d-0333-4d3c-8b1b-3acc4b9b47d3' and email='p6c-slice4-user@example.test')<>1
    or (select count(*) from auth.users where id='9dbcfe8d-0333-4d3c-8b1b-3acc4b9b47d3' or lower(email)='p6c-slice4-user@example.test')<>1
    or (select count(*) from public.profiles where user_id='9dbcfe8d-0333-4d3c-8b1b-3acc4b9b47d3' and email_snapshot='p6c-slice4-user@example.test' and status='ACTIVE')<>1
    then raise exception 'Exact synthetic Auth/profile identity mismatch'; end if;
  if (select count(*) from public.companies where id in ('74000000-0000-4000-8000-0000000000a1','74000000-0000-4000-8000-0000000000a2'))<>2 then raise exception 'Unexpected companies count'; end if;
  if (select count(*) from public.companies where id is not distinct from '74000000-0000-4000-8000-0000000000a1' and code is not distinct from 'P6C-S4-ALPHA' and name is not distinct from 'P6C Slice 4 Alpha' and legal_name is not distinct from 'P6C Slice 4 Alpha Synthetic LLC' and status is not distinct from 'ACTIVE' and notes is not distinct from 'Temporary P6C Slice 4 verification only' and created_by is not distinct from null and updated_by is not distinct from null)<>1 then raise exception 'Exact companies manifest mismatch'; end if;
  if (select count(*) from public.companies where id is not distinct from '74000000-0000-4000-8000-0000000000a2' and code is not distinct from 'P6C-S4-BETA' and name is not distinct from 'P6C Slice 4 Beta' and legal_name is not distinct from 'P6C Slice 4 Beta Synthetic LLC' and status is not distinct from 'ACTIVE' and notes is not distinct from 'Temporary P6C Slice 4 verification only' and created_by is not distinct from null and updated_by is not distinct from null)<>1 then raise exception 'Exact companies manifest mismatch'; end if;
  if (select count(*) from public.company_settings where company_id in ('74000000-0000-4000-8000-0000000000a1','74000000-0000-4000-8000-0000000000a2'))<>2 then raise exception 'Unexpected company_settings count'; end if;
  if (select count(*) from public.company_settings where company_id is not distinct from '74000000-0000-4000-8000-0000000000a1' and tenant_slug is not distinct from 'p6c-s4-alpha' and app_display_name is not distinct from 'P6C S4 Alpha' and default_locale is not distinct from 'en' and primary_color is not distinct from '#1d4ed8' and accent_color is not distinct from '#0891b2' and created_by is not distinct from null and updated_by is not distinct from null)<>1 then raise exception 'Exact company_settings manifest mismatch'; end if;
  if (select count(*) from public.company_settings where company_id is not distinct from '74000000-0000-4000-8000-0000000000a2' and tenant_slug is not distinct from 'p6c-s4-beta' and app_display_name is not distinct from 'P6C S4 Beta' and default_locale is not distinct from 'ar' and primary_color is not distinct from '#7e22ce' and accent_color is not distinct from '#c2410c' and created_by is not distinct from null and updated_by is not distinct from null)<>1 then raise exception 'Exact company_settings manifest mismatch'; end if;
  if (select count(*) from public.company_memberships where company_id in ('74000000-0000-4000-8000-0000000000a1','74000000-0000-4000-8000-0000000000a2'))<>2 then raise exception 'Unexpected company_memberships count'; end if;
  if (select count(*) from public.company_memberships where id is not distinct from '74000000-0000-4000-8000-0000000000b1' and company_id is not distinct from '74000000-0000-4000-8000-0000000000a1' and user_id is not distinct from '9dbcfe8d-0333-4d3c-8b1b-3acc4b9b47d3' and role is not distinct from 'MANAGEMENT_VIEWER' and status is not distinct from 'ACTIVE' and created_by is not distinct from null and updated_by is not distinct from null)<>1 then raise exception 'Exact company_memberships manifest mismatch'; end if;
  if (select count(*) from public.company_memberships where id is not distinct from '74000000-0000-4000-8000-0000000000b2' and company_id is not distinct from '74000000-0000-4000-8000-0000000000a2' and user_id is not distinct from '9dbcfe8d-0333-4d3c-8b1b-3acc4b9b47d3' and role is not distinct from 'MANAGEMENT_VIEWER' and status is not distinct from 'ACTIVE' and created_by is not distinct from null and updated_by is not distinct from null)<>1 then raise exception 'Exact company_memberships manifest mismatch'; end if;
  if (select count(*) from public.projects where company_id in ('74000000-0000-4000-8000-0000000000a1','74000000-0000-4000-8000-0000000000a2'))<>2 then raise exception 'Unexpected projects count'; end if;
  if (select count(*) from public.projects where id is not distinct from '74000000-0000-4000-8000-0000000000c1' and company_id is not distinct from '74000000-0000-4000-8000-0000000000a1' and code is not distinct from 'P6C-S4-PROJECT-A' and name is not distinct from 'P6C Slice 4 Project A — المشروع أ' and status is not distinct from 'ACTIVE' and created_by is not distinct from null and updated_by is not distinct from null)<>1 then raise exception 'Exact projects manifest mismatch'; end if;
  if (select count(*) from public.projects where id is not distinct from '74000000-0000-4000-8000-0000000000c2' and company_id is not distinct from '74000000-0000-4000-8000-0000000000a1' and code is not distinct from 'P6C-S4-PROJECT-B' and name is not distinct from 'P6C Slice 4 Project B — المشروع ب' and status is not distinct from 'ACTIVE' and created_by is not distinct from null and updated_by is not distinct from null)<>1 then raise exception 'Exact projects manifest mismatch'; end if;
  if (select count(*) from public.project_assignments where company_id in ('74000000-0000-4000-8000-0000000000a1','74000000-0000-4000-8000-0000000000a2'))<>1 then raise exception 'Unexpected project_assignments count'; end if;
  if (select count(*) from public.project_assignments where id is not distinct from '74000000-0000-4000-8000-0000000000d1' and company_id is not distinct from '74000000-0000-4000-8000-0000000000a1' and project_id is not distinct from '74000000-0000-4000-8000-0000000000c1' and user_id is not distinct from '9dbcfe8d-0333-4d3c-8b1b-3acc4b9b47d3' and status is not distinct from 'ACTIVE' and created_by is not distinct from null and updated_by is not distinct from null)<>1 then raise exception 'Exact project_assignments manifest mismatch'; end if;
  if (select count(*) from public.parties where company_id in ('74000000-0000-4000-8000-0000000000a1','74000000-0000-4000-8000-0000000000a2'))<>2 then raise exception 'Unexpected parties count'; end if;
  if (select count(*) from public.parties where id is not distinct from '74000000-0000-4000-8000-0000000000e1' and company_id is not distinct from '74000000-0000-4000-8000-0000000000a1' and type is not distinct from 'SUBCONTRACTOR' and code is not distinct from 'P6C-S4-SUB-001' and name is not distinct from 'P6C S4 Concrete — مقاول الخرسانة' and status is not distinct from 'ACTIVE' and created_by is not distinct from null and updated_by is not distinct from null)<>1 then raise exception 'Exact parties manifest mismatch'; end if;
  if (select count(*) from public.parties where id is not distinct from '74000000-0000-4000-8000-0000000000e2' and company_id is not distinct from '74000000-0000-4000-8000-0000000000a1' and type is not distinct from 'SUBCONTRACTOR' and code is not distinct from 'P6C-S4-SUB-002' and name is not distinct from 'P6C S4 Finishes — مقاول التشطيبات' and status is not distinct from 'ACTIVE' and created_by is not distinct from null and updated_by is not distinct from null)<>1 then raise exception 'Exact parties manifest mismatch'; end if;
  if (select count(*) from public.subcontracts where company_id in ('74000000-0000-4000-8000-0000000000a1','74000000-0000-4000-8000-0000000000a2'))<>3 then raise exception 'Unexpected subcontracts count'; end if;
  if (select count(*) from public.subcontracts where id is not distinct from '74000000-0000-4000-8000-0000000000f1' and company_id is not distinct from '74000000-0000-4000-8000-0000000000a1' and project_id is not distinct from '74000000-0000-4000-8000-0000000000c1' and subcontractor_id is not distinct from '74000000-0000-4000-8000-0000000000e1' and contract_number is not distinct from 'P6C-S4-A-001' and scope_of_work is not distinct from 'Synthetic concrete works — أعمال الخرسانة' and original_contract_value_minor is not distinct from 12500000 and approved_variations_minor is not distinct from 250000 and retention_bps is not distinct from 500 and start_date is not distinct from '2026-01-15' and expected_end_date is not distinct from '2026-12-31' and status is not distinct from 'ACTIVE' and notes is not distinct from 'Synthetic dated contract — ملاحظة تحقق' and created_by is not distinct from null and updated_by is not distinct from null)<>1 then raise exception 'Exact subcontracts manifest mismatch'; end if;
  if (select count(*) from public.subcontracts where id is not distinct from '74000000-0000-4000-8000-0000000000f2' and company_id is not distinct from '74000000-0000-4000-8000-0000000000a1' and project_id is not distinct from '74000000-0000-4000-8000-0000000000c1' and subcontractor_id is not distinct from '74000000-0000-4000-8000-0000000000e1' and contract_number is not distinct from 'P6C-S4-A-002' and scope_of_work is not distinct from 'Synthetic BIGINT precision verification only' and original_contract_value_minor is not distinct from 9007199254740993 and approved_variations_minor is not distinct from 0 and retention_bps is not distinct from 1000 and start_date is not distinct from null and expected_end_date is not distinct from null and status is not distinct from 'COMPLETED' and notes is not distinct from null and created_by is not distinct from null and updated_by is not distinct from null)<>1 then raise exception 'Exact subcontracts manifest mismatch'; end if;
  if (select count(*) from public.subcontracts where id is not distinct from '74000000-0000-4000-8000-0000000000f3' and company_id is not distinct from '74000000-0000-4000-8000-0000000000a1' and project_id is not distinct from '74000000-0000-4000-8000-0000000000c2' and subcontractor_id is not distinct from '74000000-0000-4000-8000-0000000000e2' and contract_number is not distinct from 'P6C-S4-B-001' and scope_of_work is not distinct from 'Synthetic finishes — أعمال التشطيبات' and original_contract_value_minor is not distinct from 800000 and approved_variations_minor is not distinct from -10000 and retention_bps is not distinct from 125 and start_date is not distinct from '2026-02-01' and expected_end_date is not distinct from null and status is not distinct from 'CLOSED' and notes is not distinct from null and created_by is not distinct from null and updated_by is not distinct from null)<>1 then raise exception 'Exact subcontracts manifest mismatch'; end if;
  for r in select ns.nspname,c.relname from pg_class c join pg_namespace ns on ns.oid=c.relnamespace
    where ns.nspname in ('public','private') and c.relkind in ('r','p')
      and exists (select 1 from pg_attribute x where x.attrelid=c.oid and x.attname='company_id' and not x.attisdropped)
      and not (ns.nspname='public' and c.relname in ('company_settings','company_memberships','projects','project_assignments','parties','subcontracts'))
  loop
    execute format('select count(*) from %I.%I where company_id in ($1,$2)',r.nspname,r.relname) into n using '74000000-0000-4000-8000-0000000000a1'::uuid,'74000000-0000-4000-8000-0000000000a2'::uuid;
    if n<>0 then raise exception 'Unexpected Company-scoped rows in %.%',r.nspname,r.relname; end if;
  end loop;
  if exists (select 1 from public.company_memberships where user_id='9dbcfe8d-0333-4d3c-8b1b-3acc4b9b47d3' and id not in ('74000000-0000-4000-8000-0000000000b1','74000000-0000-4000-8000-0000000000b2'))
    or exists (select 1 from public.project_assignments where user_id='9dbcfe8d-0333-4d3c-8b1b-3acc4b9b47d3' and id<>'74000000-0000-4000-8000-0000000000d1')
    or exists (select 1 from private.system_administrators where user_id='9dbcfe8d-0333-4d3c-8b1b-3acc4b9b47d3')
    then raise exception 'Unrelated user membership/assignment/platform authority'; end if;
  if exists (select 1 from public.companies c full join public.company_settings s on s.company_id=c.id where c.id is null or s.company_id is null) then raise exception 'Company/settings one-to-one mismatch'; end if;
  if (select count(*) from public.companies)<>16 or (select count(*) from public.company_settings)<>16 then raise exception 'Post-insert baseline mismatch'; end if;
end;
$fixture$;
commit;
