-- Fixture/Auth cleanup complete; retained historical support. See README.md.
-- MakerACC-Development (eqnzueginpkskbnqvgoc) ONLY. Operational fixture; NOT a migration.
begin transaction read only;
do $preflight$
declare r record; n bigint;
begin
  if (select count(*) from auth.users where id='9dbcfe8d-0333-4d3c-8b1b-3acc4b9b47d3' and email='p6c-slice4-user@example.test')<>1
    or (select count(*) from auth.users where id='9dbcfe8d-0333-4d3c-8b1b-3acc4b9b47d3' or lower(email)='p6c-slice4-user@example.test')<>1
    or (select count(*) from public.profiles where user_id='9dbcfe8d-0333-4d3c-8b1b-3acc4b9b47d3' and email_snapshot='p6c-slice4-user@example.test' and status='ACTIVE')<>1
    then raise exception 'Exact synthetic Auth/profile identity mismatch'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='companies' and column_name='id' and udt_name='uuid' and is_nullable='NO') then raise exception 'Fixture column mismatch: companies.id'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='companies' and column_name='code' and udt_name='text' and is_nullable='NO') then raise exception 'Fixture column mismatch: companies.code'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='companies' and column_name='name' and udt_name='text' and is_nullable='NO') then raise exception 'Fixture column mismatch: companies.name'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='companies' and column_name='status' and udt_name='account_status' and is_nullable='NO') then raise exception 'Fixture column mismatch: companies.status'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='companies' and column_name='created_at' and udt_name='timestamptz' and is_nullable='NO') then raise exception 'Fixture column mismatch: companies.created_at'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='companies' and column_name='updated_at' and udt_name='timestamptz' and is_nullable='NO') then raise exception 'Fixture column mismatch: companies.updated_at'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='companies' and column_name='legal_name' and udt_name='text' and is_nullable='YES') then raise exception 'Fixture column mismatch: companies.legal_name'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='companies' and column_name='trn' and udt_name='text' and is_nullable='YES') then raise exception 'Fixture column mismatch: companies.trn'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='companies' and column_name='address' and udt_name='text' and is_nullable='YES') then raise exception 'Fixture column mismatch: companies.address'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='companies' and column_name='notes' and udt_name='text' and is_nullable='YES') then raise exception 'Fixture column mismatch: companies.notes'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='companies' and column_name='created_by' and udt_name='uuid' and is_nullable='YES') then raise exception 'Fixture column mismatch: companies.created_by'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='companies' and column_name='updated_by' and udt_name='uuid' and is_nullable='YES') then raise exception 'Fixture column mismatch: companies.updated_by'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='company_memberships' and column_name='id' and udt_name='uuid' and is_nullable='NO') then raise exception 'Fixture column mismatch: company_memberships.id'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='company_memberships' and column_name='company_id' and udt_name='uuid' and is_nullable='NO') then raise exception 'Fixture column mismatch: company_memberships.company_id'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='company_memberships' and column_name='user_id' and udt_name='uuid' and is_nullable='NO') then raise exception 'Fixture column mismatch: company_memberships.user_id'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='company_memberships' and column_name='role' and udt_name='company_role' and is_nullable='NO') then raise exception 'Fixture column mismatch: company_memberships.role'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='company_memberships' and column_name='status' and udt_name='account_status' and is_nullable='NO') then raise exception 'Fixture column mismatch: company_memberships.status'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='company_memberships' and column_name='created_at' and udt_name='timestamptz' and is_nullable='NO') then raise exception 'Fixture column mismatch: company_memberships.created_at'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='company_memberships' and column_name='created_by' and udt_name='uuid' and is_nullable='YES') then raise exception 'Fixture column mismatch: company_memberships.created_by'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='company_memberships' and column_name='updated_at' and udt_name='timestamptz' and is_nullable='NO') then raise exception 'Fixture column mismatch: company_memberships.updated_at'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='company_memberships' and column_name='updated_by' and udt_name='uuid' and is_nullable='YES') then raise exception 'Fixture column mismatch: company_memberships.updated_by'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='company_settings' and column_name='company_id' and udt_name='uuid' and is_nullable='NO') then raise exception 'Fixture column mismatch: company_settings.company_id'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='company_settings' and column_name='tenant_slug' and udt_name='text' and is_nullable='NO') then raise exception 'Fixture column mismatch: company_settings.tenant_slug'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='company_settings' and column_name='app_display_name' and udt_name='text' and is_nullable='YES') then raise exception 'Fixture column mismatch: company_settings.app_display_name'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='company_settings' and column_name='default_locale' and udt_name='app_locale' and is_nullable='NO') then raise exception 'Fixture column mismatch: company_settings.default_locale'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='company_settings' and column_name='logo_url' and udt_name='text' and is_nullable='YES') then raise exception 'Fixture column mismatch: company_settings.logo_url'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='company_settings' and column_name='favicon_url' and udt_name='text' and is_nullable='YES') then raise exception 'Fixture column mismatch: company_settings.favicon_url'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='company_settings' and column_name='primary_color' and udt_name='text' and is_nullable='NO') then raise exception 'Fixture column mismatch: company_settings.primary_color'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='company_settings' and column_name='accent_color' and udt_name='text' and is_nullable='NO') then raise exception 'Fixture column mismatch: company_settings.accent_color'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='company_settings' and column_name='created_at' and udt_name='timestamptz' and is_nullable='NO') then raise exception 'Fixture column mismatch: company_settings.created_at'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='company_settings' and column_name='created_by' and udt_name='uuid' and is_nullable='YES') then raise exception 'Fixture column mismatch: company_settings.created_by'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='company_settings' and column_name='updated_at' and udt_name='timestamptz' and is_nullable='NO') then raise exception 'Fixture column mismatch: company_settings.updated_at'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='company_settings' and column_name='updated_by' and udt_name='uuid' and is_nullable='YES') then raise exception 'Fixture column mismatch: company_settings.updated_by'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='parties' and column_name='id' and udt_name='uuid' and is_nullable='NO') then raise exception 'Fixture column mismatch: parties.id'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='parties' and column_name='company_id' and udt_name='uuid' and is_nullable='NO') then raise exception 'Fixture column mismatch: parties.company_id'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='parties' and column_name='type' and udt_name='party_type' and is_nullable='NO') then raise exception 'Fixture column mismatch: parties.type'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='parties' and column_name='name' and udt_name='text' and is_nullable='NO') then raise exception 'Fixture column mismatch: parties.name'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='parties' and column_name='code' and udt_name='text' and is_nullable='YES') then raise exception 'Fixture column mismatch: parties.code'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='parties' and column_name='trn' and udt_name='text' and is_nullable='YES') then raise exception 'Fixture column mismatch: parties.trn'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='parties' and column_name='contact_person' and udt_name='text' and is_nullable='YES') then raise exception 'Fixture column mismatch: parties.contact_person'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='parties' and column_name='phone' and udt_name='text' and is_nullable='YES') then raise exception 'Fixture column mismatch: parties.phone'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='parties' and column_name='email' and udt_name='text' and is_nullable='YES') then raise exception 'Fixture column mismatch: parties.email'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='parties' and column_name='address' and udt_name='text' and is_nullable='YES') then raise exception 'Fixture column mismatch: parties.address'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='parties' and column_name='status' and udt_name='account_status' and is_nullable='NO') then raise exception 'Fixture column mismatch: parties.status'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='parties' and column_name='notes' and udt_name='text' and is_nullable='YES') then raise exception 'Fixture column mismatch: parties.notes'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='parties' and column_name='created_at' and udt_name='timestamptz' and is_nullable='NO') then raise exception 'Fixture column mismatch: parties.created_at'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='parties' and column_name='created_by' and udt_name='uuid' and is_nullable='YES') then raise exception 'Fixture column mismatch: parties.created_by'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='parties' and column_name='updated_at' and udt_name='timestamptz' and is_nullable='NO') then raise exception 'Fixture column mismatch: parties.updated_at'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='parties' and column_name='updated_by' and udt_name='uuid' and is_nullable='YES') then raise exception 'Fixture column mismatch: parties.updated_by'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='project_assignments' and column_name='id' and udt_name='uuid' and is_nullable='NO') then raise exception 'Fixture column mismatch: project_assignments.id'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='project_assignments' and column_name='company_id' and udt_name='uuid' and is_nullable='NO') then raise exception 'Fixture column mismatch: project_assignments.company_id'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='project_assignments' and column_name='project_id' and udt_name='uuid' and is_nullable='NO') then raise exception 'Fixture column mismatch: project_assignments.project_id'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='project_assignments' and column_name='user_id' and udt_name='uuid' and is_nullable='NO') then raise exception 'Fixture column mismatch: project_assignments.user_id'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='project_assignments' and column_name='status' and udt_name='account_status' and is_nullable='NO') then raise exception 'Fixture column mismatch: project_assignments.status'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='project_assignments' and column_name='created_at' and udt_name='timestamptz' and is_nullable='NO') then raise exception 'Fixture column mismatch: project_assignments.created_at'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='project_assignments' and column_name='created_by' and udt_name='uuid' and is_nullable='YES') then raise exception 'Fixture column mismatch: project_assignments.created_by'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='project_assignments' and column_name='updated_at' and udt_name='timestamptz' and is_nullable='NO') then raise exception 'Fixture column mismatch: project_assignments.updated_at'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='project_assignments' and column_name='updated_by' and udt_name='uuid' and is_nullable='YES') then raise exception 'Fixture column mismatch: project_assignments.updated_by'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='projects' and column_name='id' and udt_name='uuid' and is_nullable='NO') then raise exception 'Fixture column mismatch: projects.id'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='projects' and column_name='company_id' and udt_name='uuid' and is_nullable='NO') then raise exception 'Fixture column mismatch: projects.company_id'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='projects' and column_name='code' and udt_name='text' and is_nullable='NO') then raise exception 'Fixture column mismatch: projects.code'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='projects' and column_name='name' and udt_name='text' and is_nullable='NO') then raise exception 'Fixture column mismatch: projects.name'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='projects' and column_name='client_name' and udt_name='text' and is_nullable='YES') then raise exception 'Fixture column mismatch: projects.client_name'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='projects' and column_name='location' and udt_name='text' and is_nullable='YES') then raise exception 'Fixture column mismatch: projects.location'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='projects' and column_name='contract_number' and udt_name='text' and is_nullable='YES') then raise exception 'Fixture column mismatch: projects.contract_number'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='projects' and column_name='original_contract_value_minor' and udt_name='int8' and is_nullable='YES') then raise exception 'Fixture column mismatch: projects.original_contract_value_minor'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='projects' and column_name='budget_minor' and udt_name='int8' and is_nullable='YES') then raise exception 'Fixture column mismatch: projects.budget_minor'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='projects' and column_name='start_date' and udt_name='date' and is_nullable='YES') then raise exception 'Fixture column mismatch: projects.start_date'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='projects' and column_name='expected_completion_date' and udt_name='date' and is_nullable='YES') then raise exception 'Fixture column mismatch: projects.expected_completion_date'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='projects' and column_name='status' and udt_name='project_status' and is_nullable='NO') then raise exception 'Fixture column mismatch: projects.status'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='projects' and column_name='notes' and udt_name='text' and is_nullable='YES') then raise exception 'Fixture column mismatch: projects.notes'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='projects' and column_name='created_at' and udt_name='timestamptz' and is_nullable='NO') then raise exception 'Fixture column mismatch: projects.created_at'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='projects' and column_name='created_by' and udt_name='uuid' and is_nullable='YES') then raise exception 'Fixture column mismatch: projects.created_by'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='projects' and column_name='updated_at' and udt_name='timestamptz' and is_nullable='NO') then raise exception 'Fixture column mismatch: projects.updated_at'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='projects' and column_name='updated_by' and udt_name='uuid' and is_nullable='YES') then raise exception 'Fixture column mismatch: projects.updated_by'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='subcontracts' and column_name='id' and udt_name='uuid' and is_nullable='NO') then raise exception 'Fixture column mismatch: subcontracts.id'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='subcontracts' and column_name='company_id' and udt_name='uuid' and is_nullable='NO') then raise exception 'Fixture column mismatch: subcontracts.company_id'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='subcontracts' and column_name='project_id' and udt_name='uuid' and is_nullable='NO') then raise exception 'Fixture column mismatch: subcontracts.project_id'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='subcontracts' and column_name='subcontractor_id' and udt_name='uuid' and is_nullable='NO') then raise exception 'Fixture column mismatch: subcontracts.subcontractor_id'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='subcontracts' and column_name='contract_number' and udt_name='text' and is_nullable='NO') then raise exception 'Fixture column mismatch: subcontracts.contract_number'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='subcontracts' and column_name='scope_of_work' and udt_name='text' and is_nullable='NO') then raise exception 'Fixture column mismatch: subcontracts.scope_of_work'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='subcontracts' and column_name='original_contract_value_minor' and udt_name='int8' and is_nullable='NO') then raise exception 'Fixture column mismatch: subcontracts.original_contract_value_minor'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='subcontracts' and column_name='approved_variations_minor' and udt_name='int8' and is_nullable='NO') then raise exception 'Fixture column mismatch: subcontracts.approved_variations_minor'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='subcontracts' and column_name='retention_bps' and udt_name='int4' and is_nullable='NO') then raise exception 'Fixture column mismatch: subcontracts.retention_bps'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='subcontracts' and column_name='start_date' and udt_name='date' and is_nullable='YES') then raise exception 'Fixture column mismatch: subcontracts.start_date'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='subcontracts' and column_name='expected_end_date' and udt_name='date' and is_nullable='YES') then raise exception 'Fixture column mismatch: subcontracts.expected_end_date'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='subcontracts' and column_name='status' and udt_name='subcontract_status' and is_nullable='NO') then raise exception 'Fixture column mismatch: subcontracts.status'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='subcontracts' and column_name='notes' and udt_name='text' and is_nullable='YES') then raise exception 'Fixture column mismatch: subcontracts.notes'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='subcontracts' and column_name='created_at' and udt_name='timestamptz' and is_nullable='NO') then raise exception 'Fixture column mismatch: subcontracts.created_at'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='subcontracts' and column_name='created_by' and udt_name='uuid' and is_nullable='YES') then raise exception 'Fixture column mismatch: subcontracts.created_by'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='subcontracts' and column_name='updated_at' and udt_name='timestamptz' and is_nullable='NO') then raise exception 'Fixture column mismatch: subcontracts.updated_at'; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='subcontracts' and column_name='updated_by' and udt_name='uuid' and is_nullable='YES') then raise exception 'Fixture column mismatch: subcontracts.updated_by'; end if;
  for r in select n.nspname,c.relname,x.attname from pg_class c join pg_namespace n on n.oid=c.relnamespace join pg_attribute x on x.attrelid=c.oid
    where n.nspname in ('public','private') and c.relkind in ('r','p') and x.attnum>0 and not x.attisdropped and x.atttypid='uuid'::regtype
  loop
    execute format('select count(*) from %I.%I where %I::text like $1',r.nspname,r.relname,r.attname) into n using '74000000-0000-4000-8000-%';
    if n<>0 then raise exception 'Slice 4 namespace collision in %.%.%',r.nspname,r.relname,r.attname; end if;
  end loop;
  if exists (select 1 from public.companies where lower(btrim(code)) like 'p6c-s4-%' or name like 'P6C Slice 4%')
    or exists (select 1 from public.company_settings where tenant_slug like 'p6c-s4-%')
    or exists (select 1 from public.projects where lower(btrim(code)) like 'p6c-s4-%')
    or exists (select 1 from public.parties where lower(btrim(code)) like 'p6c-s4-%')
    or exists (select 1 from public.subcontracts where lower(btrim(contract_number)) like 'p6c-s4-%')
    or exists (select 1 from public.company_memberships where user_id='9dbcfe8d-0333-4d3c-8b1b-3acc4b9b47d3')
    or exists (select 1 from public.project_assignments where user_id='9dbcfe8d-0333-4d3c-8b1b-3acc4b9b47d3')
    or exists (select 1 from private.system_administrators where user_id='9dbcfe8d-0333-4d3c-8b1b-3acc4b9b47d3')
    then raise exception 'Fixture code/slug/number/user collision'; end if;
  if (select count(*) from public.companies)<>14 or (select count(*) from public.company_settings)<>14 then raise exception 'Expected 14/14 baseline changed'; end if;
  if exists (select 1 from public.companies c full join public.company_settings s on s.company_id=c.id where c.id is null or s.company_id is null) then raise exception 'Company/settings one-to-one mismatch'; end if;
end;
$preflight$;
select jsonb_build_object('auth_identity',1,'active_profile',1,'namespace_collisions',0,'company_code_collisions',0,'slug_collisions',0,'project_code_collisions',0,'party_code_collisions',0,'contract_number_collisions',0,'companies',14,'settings',14,'missing_or_orphan_settings',0) as preflight_passed;
rollback;
