export const payrollText={
 en:{title:'Payroll drafts',profiles:'Payroll Profiles',register:'Draft Register',scope:'Calculation only — no accounting posting or salary payment. Full-month regular salary only; no proration.',
 denied:'Payroll access is restricted to Accountant and Accounting Admin.',back:'Company workspace',signOut:'Sign out',switchCompany:'Switch Company',reload:'Reload saved data',
 loading:'Loading payroll…',error:'Request failed or outcome is uncertain. Reload saved data before trying again.',policy:'Request rejected. Check required fields, attendance review, employee eligibility, and non-negative net salary. No change was saved; reload before retrying.',
 staleError:'Inputs changed. Reload and explicitly refresh the draft before continuing.',emptyProfiles:'No payroll profiles.',emptyRows:'No eligible active employee profiles in this draft.',
 create:'Create profile',edit:'Edit profile',save:'Save profile',employee:'Employee',payrollId:'Payroll ID',type:'Payroll Type',profession:'Profession',station:'Work Station',project:'Default Project / Site (optional)',
 salary:'Monthly Salary',payment:'Payment Type (descriptive)',status:'Status',active:'Active',inactive:'Inactive',select:'Select…',none:'None',
 month:'Payroll month',generate:'Generate / Refresh draft',refreshHint:'Refresh replaces the calculated draft with current profiles, reviewed attendance and current adjustments. It does not lock attendance.',
 attendanceValid:'Attendance review current',attendanceRequired:'Attendance review required — confirm this month in Attendance before generating payroll.',attendance:'Open Attendance',
 stale:'STALE — displayed amounts are the last calculation. Refresh required.',fresh:'Current calculated draft',reviewed:'Draft review confirmed',review:'Confirm draft review',reviewConfirm:'I reviewed the current calculated draft.',
 noDraft:'No draft generated for this month.',calendar:'Calendar days',daily:'Salary/Day (approximate display only)',units:'Absence half-day units',absenceDays:'Absence days',payableDays:'Days worked / payable equivalent',
 absenceDeduction:'Absence deduction',additions:'Additions',deductions:'Other deductions',gross:'Gross Salary',net:'Net Salary',excluded:'Excluded from current draft',
 adjustments:'Manual draft adjustments',addition:'Addition',deduction:'Deduction',amount:'Amount',reason:'Reason / description (required)',changeReason:'Change reason (required)',
 add:'Add adjustment',saveAdjustment:'Save adjustment',void:'Void adjustment',voided:'Voided',adjustmentHint:'Generic calculation adjustments only. Changes require an explicit draft refresh. Clear deductions before voiding additions if needed to avoid negative net.',
 provenance:'Actor / time',employeeInactive:'Employee Party inactive',fullMonth:'Active profiles use the full selected month salary. Payroll Type and Work Station do not change calculations.',
 },
 ar:{title:'مسودات الرواتب',profiles:'ملفات الرواتب',register:'سجل المسودة',scope:'حساب فقط — لا ترحيل محاسبي ولا دفع رواتب. راتب شهري كامل فقط دون احتساب نسبي.',
 denied:'الوصول للرواتب مقتصر على المحاسب ومدير الحسابات.',back:'مساحة عمل الشركة',signOut:'تسجيل الخروج',switchCompany:'تغيير الشركة',reload:'إعادة تحميل البيانات المحفوظة',
 loading:'جارٍ تحميل الرواتب…',error:'فشل الطلب أو تعذر التأكد من النتيجة. أعد تحميل البيانات المحفوظة قبل المحاولة.',policy:'رُفض الطلب. تحقق من الحقول المطلوبة ومراجعة الحضور وأهلية الموظف وعدم سلبية صافي الراتب. لم يُحفظ التغيير؛ أعد التحميل قبل المحاولة.',
 staleError:'تغيرت المدخلات. أعد التحميل ثم حدّث حساب المسودة قبل المتابعة.',emptyProfiles:'لا توجد ملفات رواتب.',emptyRows:'لا توجد ملفات موظفين نشطة مؤهلة في هذه المسودة.',
 create:'إنشاء ملف راتب',edit:'تعديل ملف الراتب',save:'حفظ ملف الراتب',employee:'الموظف',payrollId:'رقم الرواتب',type:'نوع الرواتب',profession:'المهنة',station:'مقر العمل',project:'المشروع / الموقع الافتراضي (اختياري)',
 salary:'الراتب الشهري',payment:'طريقة الدفع (وصفية)',status:'الحالة',active:'نشط',inactive:'غير نشط',select:'اختر…',none:'بدون',
 month:'شهر الرواتب',generate:'إنشاء / تحديث حساب المسودة',refreshHint:'يستبدل التحديث حساب المسودة بالملفات الحالية والحضور المراجع والتعديلات الحالية. لا يُقفل الحضور.',
 attendanceValid:'مراجعة الحضور سارية',attendanceRequired:'مراجعة الحضور مطلوبة — أكّد مراجعة الشهر في الحضور قبل إنشاء الرواتب.',attendance:'فتح الحضور',
 stale:'غير محدثة — المبالغ المعروضة من آخر حساب. يلزم التحديث.',fresh:'المسودة المحسوبة محدثة',reviewed:'تم تأكيد مراجعة المسودة',review:'تأكيد مراجعة المسودة',reviewConfirm:'راجعت المسودة المحسوبة الحالية.',
 noDraft:'لم تُنشأ مسودة لهذا الشهر.',calendar:'أيام الشهر',daily:'الراتب / اليوم (عرض تقريبي فقط)',units:'وحدات نصف يوم غياب',absenceDays:'أيام الغياب',payableDays:'الأيام المكافئة للعمل / الاستحقاق',
 absenceDeduction:'خصم الغياب',additions:'الإضافات',deductions:'الخصومات الأخرى',gross:'إجمالي الراتب',net:'صافي الراتب',excluded:'مستبعد من المسودة الحالية',
 adjustments:'تعديلات المسودة اليدوية',addition:'إضافة',deduction:'خصم',amount:'المبلغ',reason:'السبب / الوصف (مطلوب)',changeReason:'سبب التغيير (مطلوب)',
 add:'إضافة تعديل',saveAdjustment:'حفظ التعديل',void:'إلغاء التعديل',voided:'ملغى',adjustmentHint:'تعديلات حسابية فقط. يلزم تحديث حساب المسودة بعد التغييرات. ألغِ الخصومات قبل الإضافات عند الحاجة لتجنب صافي سالب.',
 provenance:'المستخدم / الوقت',employeeInactive:'طرف الموظف غير نشط',fullMonth:'تستخدم الملفات النشطة راتب الشهر المحدد كاملاً. نوع الرواتب ومقر العمل لا يغيران الحساب.',
 }
};
export type PayrollLabels=typeof payrollText.en;
