-- Exact guarded cleanup. Replace only the empty UUID in an execution copy.
begin;select set_config('makeracc.fixture_user','',true);
do $$ declare actor uuid:=nullif(current_setting('makeracc.fixture_user'),'')::uuid;cs uuid[]:=array['86200000-0000-4000-8000-0000000000a1','86200000-0000-4000-8000-0000000000a2']::uuid[];t record;n bigint;removed integer;begin
 if actor is null or not exists(select 1 from auth.users where id=actor and email='p6c-s16-browser@example.test') then raise exception 'Exact Auth identity required';end if;
 if (select count(*) from public.companies where (id=cs[1] and code='P6C-S16-BROWSER-A' and name='Slice 16 Alpha') or (id=cs[2] and code='P6C-S16-BROWSER-B' and name='Slice 16 Beta'))<>2 then raise exception 'Company manifest mismatch';end if;
 if (select count(*) from public.company_settings where company_id=any(cs))<>2 or (select count(*) from public.company_memberships where company_id=any(cs) and user_id=actor)<>2 then raise exception 'Settings/membership mismatch';end if;
 if (select count(*) from public.projects where company_id=any(cs))<>2 or not exists(select 1 from public.projects where id='86200000-0000-4000-8000-0000000000c1' and status='ACTIVE') or not exists(select 1 from public.projects where id='86200000-0000-4000-8000-0000000000c2' and status='ACTIVE') then raise exception 'Project manifest mismatch';end if;
 if (select count(*) from public.parties where company_id=any(cs))<>3 or (select count(*) from public.parties where id in ('86200000-0000-4000-8000-0000000000b1','86200000-0000-4000-8000-0000000000b2') and type='SUBCONTRACTOR' and status='ACTIVE')<>2 or not exists(select 1 from public.parties where id='86200000-0000-4000-8000-0000000000b3' and type='SUPPLIER' and status='ACTIVE') then raise exception 'Party manifest mismatch';end if;
 if (select count(*) from public.subcontracts where company_id=any(cs))<>3 or not exists(select 1 from public.subcontracts where id='86200000-0000-4000-8000-0000000000d1' and company_id=cs[1] and project_id='86200000-0000-4000-8000-0000000000c1' and subcontractor_id='86200000-0000-4000-8000-0000000000b1' and contract_number='0001' and original_contract_value_minor=12345 and approved_variations_minor=500 and retention_bps=525 and status='ACTIVE') or not exists(select 1 from public.subcontracts where id='86200000-0000-4000-8000-0000000000d2' and contract_number='0002' and original_contract_value_minor=23456 and approved_variations_minor=0 and retention_bps=0 and status='CLOSED') or not exists(select 1 from public.subcontracts where id='86200000-0000-4000-8000-0000000000d3' and company_id=cs[2] and contract_number='0003' and original_contract_value_minor=34567 and status='ACTIVE') then raise exception 'Protected Subcontract manifest mismatch';end if;
 for t in select table_name from information_schema.columns where table_schema='public' and column_name='company_id' and table_name not in ('company_settings','company_memberships','projects','parties','subcontracts') loop execute format('select count(*) from public.%I where company_id=any($1)',t.table_name) into n using cs;if n<>0 then raise exception 'Unexpected dependency %',t.table_name;end if;end loop;
 delete from public.subcontracts where company_id=any(cs);get diagnostics removed=row_count;if removed<>3 then raise exception 'Subcontract delete mismatch';end if;delete from public.projects where company_id=any(cs);get diagnostics removed=row_count;if removed<>2 then raise exception 'Project delete mismatch';end if;delete from public.parties where company_id=any(cs);get diagnostics removed=row_count;if removed<>3 then raise exception 'Party delete mismatch';end if;delete from public.company_memberships where company_id=any(cs) and user_id=actor;get diagnostics removed=row_count;if removed<>2 then raise exception 'Membership delete mismatch';end if;delete from public.company_settings where company_id=any(cs);get diagnostics removed=row_count;if removed<>2 then raise exception 'Settings delete mismatch';end if;delete from public.companies where id=any(cs);get diagnostics removed=row_count;if removed<>2 then raise exception 'Company delete mismatch';end if;delete from public.profiles where user_id=actor;get diagnostics removed=row_count;if removed<>1 then raise exception 'Profile delete mismatch';end if;delete from auth.users where id=actor and email='p6c-s16-browser@example.test';get diagnostics removed=row_count;if removed<>1 then raise exception 'Auth delete mismatch';end if;
 if (select count(*) from public.companies)<>14 or (select count(*) from public.company_settings)<>14 or exists(select 1 from public.companies c left join public.company_settings s on s.company_id=c.id where s.company_id is null) or exists(select 1 from public.company_settings s left join public.companies c on c.id=s.company_id where c.id is null) then raise exception 'Global integrity mismatch';end if;
end $$;commit;
